version: 2

project_name: killswitch

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: killswitch
    main: ./cmd/killswitch
    binary: killswitch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm64
  - id: killswitch-cli
    main: ./cmd/killswitch-cli
    binary: killswitch-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm64
  - id: killswitch-user
    main: ./cmd/killswitch-user
    binary: killswitch-user
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm64

archives:
  - id: killswitch
    ids:
      - killswitch
      - killswitch-user
      - killswitch-cli
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i686
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    files:
      - LICENSE-MIT
      - LICENSE-GPL
      - README.md
      - killswitch.example.json
      - killswitch-user.example.json

checksum:
  name_template: checksums.txt

changelog:
  disable: true

nfpms:
  - id: killswitch
    package_name: killswitch
    ids:
      - killswitch
      - killswitch-user
      - killswitch-cli
    vendor: asciimoth
    homepage: https://github.com/asciimoth/killswitch
    maintainer: "{{ .Env.PACKAGE_MAINTAINER }}"
    description: Linux eBPF network kill switch for vpn apps an beyond
    license: MIT OR GPL-3.0-or-later
    section: net
    priority: optional
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    rpm:
      group: Applications/Internet

signs:
  - artifacts: all
    cmd: gpg
    args:
      - --batch
      - --yes
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

release:
  github:
    owner: asciimoth
    name: killswitch
  draft: false
  prerelease: auto
  mode: replace

aurs:
  - name: killswitch-bin
    homepage: https://github.com/asciimoth/killswitch
    description: Linux eBPF network kill switch for vpn apps an beyond
    maintainers:
      - "{{ .Env.PACKAGE_MAINTAINER }}"
    license: MIT OR GPL-3.0-or-later
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git"
    git_ssh_command: '{{ .Env.SSH_BIN }} -i "{{ .KeyPath }}" -o StrictHostKeyChecking=accept-new -F /dev/null'
    provides:
      - killswitch
      - killswitch-cli
      - killswitch-user
    depends:
      - glibc
    package: |-
      install -Dm755 "./killswitch" "${pkgdir}/usr/bin/killswitch"
      install -Dm755 "./killswitch-cli" "${pkgdir}/usr/bin/killswitch-cli"
      install -Dm755 "./killswitch-user" "${pkgdir}/usr/bin/killswitch-user"

publishers:
  - name: "GH Pages deb/rpm repo"
    cmd: "{{ .Env.MYREPO }}/maintain add {{ abs .ArtifactPath }}"

