// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type killswitchRuntimeConfig struct {
	_         structs.HostLayout
	AllowAll  uint8
	EnableV4  uint8
	EnableV6  uint8
	Reserved0 uint8
}

// loadKillswitch returns the embedded CollectionSpec for killswitch.
func loadKillswitch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KillswitchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load killswitch: %w", err)
	}

	return spec, err
}

// loadKillswitchObjects loads killswitch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*killswitchObjects
//	*killswitchPrograms
//	*killswitchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKillswitchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKillswitch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// killswitchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killswitchSpecs struct {
	killswitchProgramSpecs
	killswitchMapSpecs
	killswitchVariableSpecs
}

// killswitchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killswitchProgramSpecs struct {
	KillswitchEgress *ebpf.ProgramSpec `ebpf:"killswitch_egress"`
}

// killswitchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killswitchMapSpecs struct {
	BootstrapEvents *ebpf.MapSpec `ebpf:"bootstrap_events"`
	RuntimeConfig   *ebpf.MapSpec `ebpf:"runtime_config"`
}

// killswitchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killswitchVariableSpecs struct {
}

// killswitchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKillswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type killswitchObjects struct {
	killswitchPrograms
	killswitchMaps
	killswitchVariables
}

func (o *killswitchObjects) Close() error {
	return _KillswitchClose(
		&o.killswitchPrograms,
		&o.killswitchMaps,
	)
}

// killswitchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKillswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type killswitchMaps struct {
	BootstrapEvents *ebpf.Map `ebpf:"bootstrap_events"`
	RuntimeConfig   *ebpf.Map `ebpf:"runtime_config"`
}

func (m *killswitchMaps) Close() error {
	return _KillswitchClose(
		m.BootstrapEvents,
		m.RuntimeConfig,
	)
}

// killswitchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKillswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type killswitchVariables struct {
}

// killswitchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKillswitchObjects or ebpf.CollectionSpec.LoadAndAssign.
type killswitchPrograms struct {
	KillswitchEgress *ebpf.Program `ebpf:"killswitch_egress"`
}

func (p *killswitchPrograms) Close() error {
	return _KillswitchClose(
		p.KillswitchEgress,
	)
}

func _KillswitchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed killswitch_bpfeb.o
var _KillswitchBytes []byte
