//go:build linux

package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/netip"
	"os"
	"os/signal"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"sync"
	"syscall"

	"github.com/asciimoth/killswitch/internal/adminapi"
	"github.com/asciimoth/killswitch/internal/policy"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

const (
	bootstrapARP    = 1
	bootstrapDHCPv4 = 2
	bootstrapDHCPv6 = 3
	bootstrapICMPv6 = 4

	ipProtoTCP = policy.IPProtoTCP
	ipProtoUDP = policy.IPProtoUDP

	defaultConfigPath = "/etc/killswitch/killswitch.json"
)

// runtimeConfig mirrors struct runtime_config in killswitch.c. Keep this type
// byte-sized so map updates are ABI-stable across Go and C.
type runtimeConfig struct {
	AllowAll uint8
	EnableV4 uint8
	EnableV6 uint8
	Reserved uint8
}

// bootstrapEvent mirrors struct bootstrap_event in killswitch.c. The eBPF
// program emits only bootstrap pass events so this channel remains low volume.
type bootstrapEvent struct {
	TimestampNS uint64
	Ifindex     uint32
	EthProto    uint16
	Reason      uint8
	IPProto     uint8
	IPv4Saddr   uint32
	IPv4Daddr   uint32
	IPv6Saddr   [16]byte
	IPv6Daddr   [16]byte
	SourcePort  uint16
	DestPort    uint16
	ICMPv6Type  uint8
	VLANDepth   uint8
	Reserved    uint16
}

// portKey mirrors struct port_key in killswitch.c. Ports are stored in network
// byte order because the eBPF parser compares them directly with packet fields.
type portKey struct {
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

type markPolicyKey struct {
	Ifindex uint32
	Mark    uint32
}

type portPolicyKey struct {
	Ifindex  uint32
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

// ipv6AddrKey stores an unscoped IPv6 address in parsed allow-rule config.
type ipv6AddrKey struct {
	Addr [16]byte
}

type v4HostPolicyKey struct {
	Ifindex uint32
	Daddr   uint32
}

type v6HostPolicyKey struct {
	Ifindex uint32
	Addr    [16]byte
}

// hostport4Key mirrors struct hostport4_key in killswitch.c. Explicit padding
// keeps the Go value layout aligned with the C map key ABI generated by clang.
type hostport4Key struct {
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

// hostport6Key mirrors struct hostport6_key in killswitch.c.
type hostport6Key struct {
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type hostport4PolicyKey struct {
	Ifindex   uint32
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type hostport6PolicyKey struct {
	Ifindex   uint32
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type options struct {
	InterfaceTypes          []string
	InterfaceNames          []string
	InterfaceRegexps        []string
	IgnoredInterfaceTypes   []string
	IgnoredInterfaceNames   []string
	IgnoredInterfaceRegexps []string
	AdminAPI                adminAPIOptions
	allowRules
	Rulesets []ruleset
}

type allowRules struct {
	AllowAll       bool
	EnableV4       bool
	EnableV6       bool
	AllowedMarks   []uint32
	AllowedPorts   []portKey
	AllowedV4Hosts []uint32
	AllowedV6Hosts []ipv6AddrKey
	AllowedV4Pairs []hostport4Key
	AllowedV6Pairs []hostport6Key
}

type ruleset struct {
	Name     string
	Disabled bool
	MatchAll bool
	Trigger  rulesetTrigger
	allowRules
}

type rulesetTrigger struct {
	InterfaceTypes   []string
	InterfaceNames   []string
	InterfaceRegexps []string
	IPAddrs          []netip.Addr
}

type configFile struct {
	InterfaceTypes          []string                 `json:"interface_types"`
	InterfaceNames          []string                 `json:"interface_names"`
	InterfaceRegexps        []string                 `json:"interface_regexps"`
	IgnoredInterfaceTypes   []string                 `json:"ignored_interface_types"`
	IgnoredInterfaceNames   []string                 `json:"ignored_interface_names"`
	IgnoredInterfaceRegexps []string                 `json:"ignored_interface_regexps"`
	AdminAPI                adminAPIConfig           `json:"admin_api"`
	AllowAll                bool                     `json:"allow_all"`
	EnableV4                bool                     `json:"enable_v4"`
	EnableV6                bool                     `json:"enable_v6"`
	AllowedMarks            []string                 `json:"allowed_marks"`
	AllowedPorts            []string                 `json:"allowed_ports"`
	AllowedV4Hosts          []string                 `json:"allowed_v4_hosts"`
	AllowedV6Hosts          []string                 `json:"allowed_v6_hosts"`
	AllowedV4Pairs          []string                 `json:"allowed_v4_hostports"`
	AllowedV6Pairs          []string                 `json:"allowed_v6_hostports"`
	Rulesets                map[string]rulesetConfig `json:"rulesets"`
}

type rulesetConfig struct {
	Disabled       bool          `json:"disabled"`
	Match          string        `json:"match"`
	MatchAll       bool          `json:"match_all"`
	Trigger        triggerConfig `json:"trigger"`
	AllowAll       bool          `json:"allow_all"`
	EnableV4       bool          `json:"enable_v4"`
	EnableV6       bool          `json:"enable_v6"`
	AllowedMarks   []string      `json:"allowed_marks"`
	AllowedPorts   []string      `json:"allowed_ports"`
	AllowedV4Hosts []string      `json:"allowed_v4_hosts"`
	AllowedV6Hosts []string      `json:"allowed_v6_hosts"`
	AllowedV4Pairs []string      `json:"allowed_v4_hostports"`
	AllowedV6Pairs []string      `json:"allowed_v6_hostports"`
}

type triggerConfig struct {
	InterfaceTypes   []string `json:"interface_types"`
	InterfaceNames   []string `json:"interface_names"`
	InterfaceRegexps []string `json:"interface_regexps"`
	IPAddrs          []string `json:"ip_addrs"`
}

type interfaceInfo struct {
	Index int
	Name  string
	Type  string
	Addrs []netip.Addr
}

type attachedInterface struct {
	link link.Link
	info interfaceInfo
}

type egressManager struct {
	mu       sync.Mutex
	program  *ebpf.Program
	attached map[int]attachedInterface
}

type policyManager struct {
	mu            sync.Mutex
	objs          *killswitchObjects
	opts          options
	tmpRulesets   map[string]temporaryRuleset
	forceRulesets map[string]map[string]map[string]int
	current       map[int]interfacePolicy
	set           bool
}

type interfacePolicy struct {
	Info              interfaceInfo
	Rules             allowRules
	ActiveRulesets    []string
	ForcedRulesets    []string
	TemporaryRulesets []string
}

func main() {
	configPath, err := parseArgs(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}

	opts, err := loadOptions(configPath, os.Stdin)
	if err != nil {
		log.Fatal(err)
	}

	if err := run(context.Background(), opts); err != nil {
		log.Fatal(err)
	}
}

func parseArgs(args []string) (string, error) {
	switch len(args) {
	case 0:
		return defaultConfigPath, nil
	case 1:
		return args[0], nil
	default:
		return "", fmt.Errorf("expected at most one config path argument, got: %s", strings.Join(args, " "))
	}
}

func loadOptions(configPath string, stdin io.Reader) (options, error) {
	var reader io.Reader
	if configPath == "-" {
		log.Print("Loading config from stdin")
		reader = stdin
	} else {
		log.Printf("Loading config from %s", configPath)
		file, err := os.Open(configPath)
		if err != nil {
			return options{}, fmt.Errorf("open config %q: %w", configPath, err)
		}
		defer file.Close() //nolint:errcheck
		reader = file
	}

	var cfg configFile
	decoder := json.NewDecoder(reader)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&cfg); err != nil {
		return options{}, fmt.Errorf("decode config: %w", err)
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return options{}, errors.New("decode config: multiple JSON values")
	}

	return configToOptions(cfg)
}

func configToOptions(cfg configFile) (options, error) {
	opts := options{
		InterfaceTypes:          cfg.InterfaceTypes,
		InterfaceNames:          cfg.InterfaceNames,
		InterfaceRegexps:        cfg.InterfaceRegexps,
		IgnoredInterfaceTypes:   cfg.IgnoredInterfaceTypes,
		IgnoredInterfaceNames:   cfg.IgnoredInterfaceNames,
		IgnoredInterfaceRegexps: cfg.IgnoredInterfaceRegexps,
		AdminAPI:                adminAPIOptionsFromConfig(cfg.AdminAPI),
		allowRules: allowRules{
			AllowAll: cfg.AllowAll,
			EnableV4: cfg.EnableV4,
			EnableV6: cfg.EnableV6,
		},
	}
	if len(opts.InterfaceTypes) == 0 && len(opts.InterfaceNames) == 0 && len(opts.InterfaceRegexps) == 0 {
		return options{}, errors.New("at least one interface_types, interface_names, or interface_regexps entry is required")
	}
	if err := validateAdminAPIOptions(opts.AdminAPI); err != nil {
		return options{}, err
	}

	for _, pattern := range opts.InterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return options{}, fmt.Errorf("compile interface regexp %q: %w", pattern, err)
		}
	}
	for _, pattern := range opts.IgnoredInterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return options{}, fmt.Errorf("compile ignored interface regexp %q: %w", pattern, err)
		}
	}
	var err error
	if opts.AllowedMarks, err = policy.ParseAllowedMarks(cfg.AllowedMarks); err != nil {
		return options{}, err
	}
	if opts.AllowedPorts, err = allowedPortKeys(cfg.AllowedPorts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Hosts, err = allowedV4HostKeys(cfg.AllowedV4Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Hosts, err = allowedV6HostKeys(cfg.AllowedV6Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Pairs, err = allowedV4HostportKeys(cfg.AllowedV4Pairs); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Pairs, err = allowedV6HostportKeys(cfg.AllowedV6Pairs); err != nil {
		return options{}, err
	}
	if opts.Rulesets, err = rulesetsFromConfig(cfg.Rulesets); err != nil {
		return options{}, err
	}

	return opts, nil
}

func rulesetsFromConfig(configs map[string]rulesetConfig) ([]ruleset, error) {
	rulesets := make([]ruleset, 0, len(configs))
	names := make([]string, 0, len(configs))
	for name := range configs {
		if name == "" {
			return nil, errors.New("ruleset name is required")
		}
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		cfg := configs[name]

		matchAll, err := parseRulesetMatch(cfg)
		if err != nil {
			return nil, fmt.Errorf("ruleset %q: %w", name, err)
		}

		trigger, err := triggerFromConfig(cfg.Trigger)
		if err != nil {
			return nil, fmt.Errorf("ruleset %q: %w", name, err)
		}

		rules, err := allowRulesFromConfig(cfg)
		if err != nil {
			return nil, fmt.Errorf("ruleset %q: %w", name, err)
		}

		rulesets = append(rulesets, ruleset{
			Name:       name,
			Disabled:   cfg.Disabled,
			MatchAll:   matchAll,
			Trigger:    trigger,
			allowRules: rules,
		})
	}
	return rulesets, nil
}

func parseRulesetMatch(cfg rulesetConfig) (bool, error) {
	switch strings.ToLower(cfg.Match) {
	case "", "or":
		return cfg.MatchAll, nil
	case "and":
		return true, nil
	default:
		return false, fmt.Errorf("match must be \"and\" or \"or\", got %q", cfg.Match)
	}
}

func triggerFromConfig(cfg triggerConfig) (rulesetTrigger, error) {
	trigger := rulesetTrigger{
		InterfaceTypes:   cfg.InterfaceTypes,
		InterfaceNames:   cfg.InterfaceNames,
		InterfaceRegexps: cfg.InterfaceRegexps,
	}
	for _, pattern := range trigger.InterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return rulesetTrigger{}, fmt.Errorf("compile trigger interface regexp %q: %w", pattern, err)
		}
	}
	for _, value := range cfg.IPAddrs {
		addr, err := netip.ParseAddr(value)
		if err != nil {
			return rulesetTrigger{}, fmt.Errorf("parse trigger ip_addrs %q: %w", value, err)
		}
		trigger.IPAddrs = append(trigger.IPAddrs, addr.Unmap())
	}
	if len(trigger.InterfaceTypes) == 0 && len(trigger.InterfaceNames) == 0 && len(trigger.InterfaceRegexps) == 0 && len(trigger.IPAddrs) == 0 {
		return rulesetTrigger{}, errors.New("trigger requires at least one interface_types, interface_names, interface_regexps, or ip_addrs entry")
	}
	return trigger, nil
}

func allowRulesFromConfig(cfg rulesetConfig) (allowRules, error) {
	rules := allowRules{
		AllowAll: cfg.AllowAll,
		EnableV4: cfg.EnableV4,
		EnableV6: cfg.EnableV6,
	}
	var err error
	if rules.AllowedMarks, err = policy.ParseAllowedMarks(cfg.AllowedMarks); err != nil {
		return allowRules{}, err
	}
	if rules.AllowedPorts, err = allowedPortKeys(cfg.AllowedPorts); err != nil {
		return allowRules{}, err
	}
	if rules.AllowedV4Hosts, err = allowedV4HostKeys(cfg.AllowedV4Hosts); err != nil {
		return allowRules{}, err
	}
	if rules.AllowedV6Hosts, err = allowedV6HostKeys(cfg.AllowedV6Hosts); err != nil {
		return allowRules{}, err
	}
	if rules.AllowedV4Pairs, err = allowedV4HostportKeys(cfg.AllowedV4Pairs); err != nil {
		return allowRules{}, err
	}
	if rules.AllowedV6Pairs, err = allowedV6HostportKeys(cfg.AllowedV6Pairs); err != nil {
		return allowRules{}, err
	}
	return rules, nil
}

func applyAdminMutation(req adminapi.MutationRequest, policies *policyManager, manager *egressManager, reconcileMu *sync.Mutex) adminapi.MutationResult {
	reconcileMu.Lock()
	defer reconcileMu.Unlock()

	next, err := mutateOptions(policies.optionsSnapshot(), req)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}

	policies.replaceOptions(next)
	if _, err := manager.reconcileCurrent(next, false); err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	changed, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	return adminapi.MutationResult{OK: true, Changed: changed, Config: policies.configSnapshot()}
}

func applyTemporaryRulesetMutation(owner string, req adminapi.MutationRequest, policies *policyManager, manager *egressManager, reconcileMu *sync.Mutex) adminapi.MutationResult {
	reconcileMu.Lock()
	defer reconcileMu.Unlock()

	switch req.Operation {
	case adminapi.MutationAdd, adminapi.MutationSet:
		rules, err := allowRulesFromAPI(req.Policy, req.Value)
		if err != nil {
			return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
		}
		if len(req.Interfaces) == 0 {
			return adminapi.MutationResult{OK: false, Error: "tmp_ruleset requires at least one interface name", Config: policies.configSnapshot()}
		}
		policies.setTemporaryRuleset(owner, uniqueSortedStrings(req.Interfaces), rules)
	case adminapi.MutationRemove:
		policies.removeTemporaryRuleset(owner)
	default:
		return adminapi.MutationResult{OK: false, Error: fmt.Sprintf("unsupported mutation operation %q", req.Operation), Config: policies.configSnapshot()}
	}

	changed, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	return adminapi.MutationResult{OK: true, Changed: changed, Config: policies.configSnapshot()}
}

func applyForceRulesetMutation(owner string, req adminapi.MutationRequest, policies *policyManager, manager *egressManager, reconcileMu *sync.Mutex) adminapi.MutationResult {
	reconcileMu.Lock()
	defer reconcileMu.Unlock()

	if req.Ruleset == "" {
		return adminapi.MutationResult{OK: false, Error: "ruleset name is required", Config: policies.configSnapshot()}
	}
	switch req.Operation {
	case adminapi.MutationAdd, adminapi.MutationSet:
		if len(req.Interfaces) == 0 {
			return adminapi.MutationResult{OK: false, Error: "force_ruleset requires at least one interface name", Config: policies.configSnapshot()}
		}
		if !policies.forceActivateRuleset(owner, req.Ruleset, uniqueSortedStrings(req.Interfaces), req.Operation == adminapi.MutationSet) {
			return adminapi.MutationResult{OK: false, Error: fmt.Sprintf("ruleset %q does not exist", req.Ruleset), Config: policies.configSnapshot()}
		}
	case adminapi.MutationRemove:
		policies.releaseForceRuleset(owner, req.Ruleset, uniqueSortedStrings(req.Interfaces))
	default:
		return adminapi.MutationResult{OK: false, Error: fmt.Sprintf("unsupported mutation operation %q", req.Operation), Config: policies.configSnapshot()}
	}

	policyChanged, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	return adminapi.MutationResult{OK: true, Changed: policyChanged, Config: policies.configSnapshot()}
}

func removeTemporaryRuleset(owner string, policies *policyManager, manager *egressManager, reconcileMu *sync.Mutex) adminapi.MutationResult {
	reconcileMu.Lock()
	defer reconcileMu.Unlock()

	if !policies.removeTemporaryRuleset(owner) {
		return adminapi.MutationResult{OK: true, Changed: false, Config: policies.configSnapshot()}
	}
	changed, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	return adminapi.MutationResult{OK: true, Changed: changed, Config: policies.configSnapshot()}
}

func removeForceRulesets(owner string, policies *policyManager, manager *egressManager, reconcileMu *sync.Mutex) adminapi.MutationResult {
	reconcileMu.Lock()
	defer reconcileMu.Unlock()

	if !policies.removeForceRulesets(owner) {
		return adminapi.MutationResult{OK: true, Changed: false, Config: policies.configSnapshot()}
	}
	policyChanged, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return adminapi.MutationResult{OK: false, Error: err.Error(), Config: policies.configSnapshot()}
	}
	return adminapi.MutationResult{OK: true, Changed: policyChanged, Config: policies.configSnapshot()}
}

func mutateOptions(opts options, req adminapi.MutationRequest) (options, error) {
	next := cloneOptions(opts)
	if strings.HasPrefix(req.Target, "admin_api") || req.Target == "admin_api" {
		return options{}, errors.New("admin_api configuration cannot be mutated via admin API")
	}
	switch req.Operation {
	case adminapi.MutationAdd, adminapi.MutationRemove, adminapi.MutationSet:
	default:
		return options{}, fmt.Errorf("unsupported mutation operation %q", req.Operation)
	}
	if req.Target == "" {
		return options{}, errors.New("mutation target is required")
	}

	switch req.Target {
	case "interface_types":
		if err := mutateStringList(&next.InterfaceTypes, req); err != nil {
			return options{}, err
		}
	case "interface_names":
		if err := mutateStringList(&next.InterfaceNames, req); err != nil {
			return options{}, err
		}
	case "interface_regexps":
		if err := mutateStringList(&next.InterfaceRegexps, req); err != nil {
			return options{}, err
		}
		if err := validateRegexps("interface_regexps", next.InterfaceRegexps); err != nil {
			return options{}, err
		}
	case "ignored_interface_types":
		if err := mutateStringList(&next.IgnoredInterfaceTypes, req); err != nil {
			return options{}, err
		}
	case "ignored_interface_names":
		if err := mutateStringList(&next.IgnoredInterfaceNames, req); err != nil {
			return options{}, err
		}
	case "ignored_interface_regexps":
		if err := mutateStringList(&next.IgnoredInterfaceRegexps, req); err != nil {
			return options{}, err
		}
		if err := validateRegexps("ignored_interface_regexps", next.IgnoredInterfaceRegexps); err != nil {
			return options{}, err
		}
	case "base_policy":
		if req.Operation != adminapi.MutationSet {
			return options{}, errors.New("base_policy only supports set")
		}
		rules, err := allowRulesFromAPI(req.Policy, req.Value)
		if err != nil {
			return options{}, err
		}
		next.allowRules = rules
	case "ruleset":
		if err := mutateWholeRuleset(&next.Rulesets, req); err != nil {
			return options{}, err
		}
	default:
		if strings.HasPrefix(req.Target, "base_policy.") {
			if err := mutateAllowRulesField(&next.allowRules, strings.TrimPrefix(req.Target, "base_policy."), req); err != nil {
				return options{}, err
			}
		} else if strings.HasPrefix(req.Target, "ruleset.") {
			if err := mutateRulesetField(&next.Rulesets, strings.TrimPrefix(req.Target, "ruleset."), req); err != nil {
				return options{}, err
			}
		} else {
			return options{}, fmt.Errorf("unsupported mutation target %q", req.Target)
		}
	}

	if len(next.InterfaceTypes) == 0 && len(next.InterfaceNames) == 0 && len(next.InterfaceRegexps) == 0 {
		return options{}, errors.New("at least one interface_types, interface_names, or interface_regexps entry is required")
	}
	return next, nil
}

func mutateStringList(dst *[]string, req adminapi.MutationRequest) error {
	values, err := mutationStringValues(req)
	if err != nil {
		return err
	}
	switch req.Operation {
	case adminapi.MutationAdd:
		*dst = uniqueStrings(append(*dst, values...))
	case adminapi.MutationRemove:
		*dst = removeStrings(*dst, values)
	case adminapi.MutationSet:
		*dst = uniqueStrings(values)
	}
	return nil
}

func mutationStringValues(req adminapi.MutationRequest) ([]string, error) {
	if len(req.Values) > 0 {
		return cloneStrings(req.Values), nil
	}
	if len(req.Value) == 0 {
		return nil, errors.New("mutation values are required")
	}
	var values []string
	if err := json.Unmarshal(req.Value, &values); err == nil {
		return values, nil
	}
	var value string
	if err := json.Unmarshal(req.Value, &value); err != nil {
		return nil, fmt.Errorf("decode mutation value as string or string array: %w", err)
	}
	return []string{value}, nil
}

func mutateAllowRulesField(rules *allowRules, field string, req adminapi.MutationRequest) error {
	switch field {
	case "allow_all":
		return mutateBool(&rules.AllowAll, req)
	case "enable_v4":
		return mutateBool(&rules.EnableV4, req)
	case "enable_v6":
		return mutateBool(&rules.EnableV6, req)
	case "allowed_marks", "allowed_ports", "allowed_v4_hosts", "allowed_v6_hosts", "allowed_v4_hostports", "allowed_v6_hostports":
		api := apiAllowRules(*rules)
		if err := mutateAPIAllowRulesField(&api, field, req); err != nil {
			return err
		}
		parsed, err := allowRulesFromAPI(&api, nil)
		if err != nil {
			return err
		}
		*rules = parsed
		return nil
	default:
		return fmt.Errorf("unsupported allow rules field %q", field)
	}
}

func mutateAPIAllowRulesField(rules *adminapi.AllowRules, field string, req adminapi.MutationRequest) error {
	switch field {
	case "allowed_marks":
		return mutateStringList(&rules.AllowedMarks, req)
	case "allowed_ports":
		return mutateStringList(&rules.AllowedPorts, req)
	case "allowed_v4_hosts":
		return mutateStringList(&rules.AllowedV4Hosts, req)
	case "allowed_v6_hosts":
		return mutateStringList(&rules.AllowedV6Hosts, req)
	case "allowed_v4_hostports":
		return mutateStringList(&rules.AllowedV4Pairs, req)
	case "allowed_v6_hostports":
		return mutateStringList(&rules.AllowedV6Pairs, req)
	default:
		return fmt.Errorf("unsupported allow rules field %q", field)
	}
}

func mutateBool(dst *bool, req adminapi.MutationRequest) error {
	if req.Operation != adminapi.MutationSet {
		return errors.New("boolean fields only support set")
	}
	if len(req.Value) == 0 {
		return errors.New("boolean mutation value is required")
	}
	var value bool
	if err := json.Unmarshal(req.Value, &value); err != nil {
		return fmt.Errorf("decode boolean mutation value: %w", err)
	}
	*dst = value
	return nil
}

func mutateWholeRuleset(rulesets *[]ruleset, req adminapi.MutationRequest) error {
	if req.Ruleset == "" {
		return errors.New("ruleset name is required")
	}
	switch req.Operation {
	case adminapi.MutationRemove:
		*rulesets = removeRuleset(*rulesets, req.Ruleset)
		return nil
	case adminapi.MutationAdd, adminapi.MutationSet:
		rulesetDef, err := rulesetFromAPI(req.Ruleset, req.RulesetDef, req.Value)
		if err != nil {
			return err
		}
		if req.Operation == adminapi.MutationAdd && findRuleset(*rulesets, req.Ruleset) >= 0 {
			return fmt.Errorf("ruleset %q already exists", req.Ruleset)
		}
		upsertRuleset(rulesets, rulesetDef)
		return nil
	default:
		return fmt.Errorf("unsupported ruleset operation %q", req.Operation)
	}
}

func mutateRulesetField(rulesets *[]ruleset, field string, req adminapi.MutationRequest) error {
	if req.Ruleset == "" {
		return errors.New("ruleset name is required")
	}
	idx := findRuleset(*rulesets, req.Ruleset)
	if idx < 0 {
		return fmt.Errorf("ruleset %q does not exist", req.Ruleset)
	}
	rs := (*rulesets)[idx]
	switch field {
	case "disabled":
		if err := mutateBool(&rs.Disabled, req); err != nil {
			return err
		}
	case "match_all":
		if err := mutateBool(&rs.MatchAll, req); err != nil {
			return err
		}
	case "trigger.interface_types":
		if err := mutateStringList(&rs.Trigger.InterfaceTypes, req); err != nil {
			return err
		}
	case "trigger.interface_names":
		if err := mutateStringList(&rs.Trigger.InterfaceNames, req); err != nil {
			return err
		}
	case "trigger.interface_regexps":
		if err := mutateStringList(&rs.Trigger.InterfaceRegexps, req); err != nil {
			return err
		}
		if err := validateRegexps("ruleset trigger interface_regexps", rs.Trigger.InterfaceRegexps); err != nil {
			return err
		}
	case "trigger.ip_addrs":
		apiTrigger := adminapi.RulesetTrigger{IPAddrs: apiAddrs(rs.Trigger.IPAddrs)}
		if err := mutateStringList(&apiTrigger.IPAddrs, req); err != nil {
			return err
		}
		trigger, err := triggerFromConfig(triggerConfig{
			InterfaceTypes:   rs.Trigger.InterfaceTypes,
			InterfaceNames:   rs.Trigger.InterfaceNames,
			InterfaceRegexps: rs.Trigger.InterfaceRegexps,
			IPAddrs:          apiTrigger.IPAddrs,
		})
		if err != nil {
			return err
		}
		rs.Trigger = trigger
	case "policy.allow_all", "policy.enable_v4", "policy.enable_v6",
		"policy.allowed_marks", "policy.allowed_ports", "policy.allowed_v4_hosts",
		"policy.allowed_v6_hosts", "policy.allowed_v4_hostports", "policy.allowed_v6_hostports":
		if err := mutateAllowRulesField(&rs.allowRules, strings.TrimPrefix(field, "policy."), req); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unsupported ruleset field %q", field)
	}
	if len(rs.Trigger.InterfaceTypes) == 0 && len(rs.Trigger.InterfaceNames) == 0 && len(rs.Trigger.InterfaceRegexps) == 0 && len(rs.Trigger.IPAddrs) == 0 {
		return errors.New("trigger requires at least one interface_types, interface_names, interface_regexps, or ip_addrs entry")
	}
	(*rulesets)[idx] = rs
	sortRulesets(*rulesets)
	return nil
}

func allowRulesFromAPI(policyPtr *adminapi.AllowRules, raw json.RawMessage) (allowRules, error) {
	var policy adminapi.AllowRules
	if policyPtr != nil {
		policy = *policyPtr
	} else {
		if len(raw) == 0 {
			return allowRules{}, errors.New("allow rules value is required")
		}
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&policy); err != nil {
			return allowRules{}, fmt.Errorf("decode allow rules: %w", err)
		}
		if decoder.Decode(&struct{}{}) != io.EOF {
			return allowRules{}, errors.New("decode allow rules: multiple JSON values")
		}
	}
	return allowRulesFromConfig(rulesetConfig{
		AllowAll:       policy.AllowAll,
		EnableV4:       policy.EnableV4,
		EnableV6:       policy.EnableV6,
		AllowedMarks:   policy.AllowedMarks,
		AllowedPorts:   policy.AllowedPorts,
		AllowedV4Hosts: policy.AllowedV4Hosts,
		AllowedV6Hosts: policy.AllowedV6Hosts,
		AllowedV4Pairs: policy.AllowedV4Pairs,
		AllowedV6Pairs: policy.AllowedV6Pairs,
	})
}

func rulesetFromAPI(name string, rulesetPtr *adminapi.RulesetMutation, raw json.RawMessage) (ruleset, error) {
	var api adminapi.RulesetMutation
	if rulesetPtr != nil {
		api = *rulesetPtr
	} else {
		if len(raw) == 0 {
			return ruleset{}, errors.New("ruleset value is required")
		}
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&api); err != nil {
			return ruleset{}, fmt.Errorf("decode ruleset: %w", err)
		}
		if decoder.Decode(&struct{}{}) != io.EOF {
			return ruleset{}, errors.New("decode ruleset: multiple JSON values")
		}
	}

	trigger, err := triggerFromConfig(triggerConfig{
		InterfaceTypes:   api.Trigger.InterfaceTypes,
		InterfaceNames:   api.Trigger.InterfaceNames,
		InterfaceRegexps: api.Trigger.InterfaceRegexps,
		IPAddrs:          api.Trigger.IPAddrs,
	})
	if err != nil {
		return ruleset{}, err
	}
	rules, err := allowRulesFromAPI(&api.Policy, nil)
	if err != nil {
		return ruleset{}, err
	}
	return ruleset{Name: name, Disabled: api.Disabled, MatchAll: api.MatchAll, Trigger: trigger, allowRules: rules}, nil
}

func validateRegexps(field string, values []string) error {
	for _, pattern := range values {
		if _, err := regexp.Compile(pattern); err != nil {
			return fmt.Errorf("compile %s %q: %w", field, pattern, err)
		}
	}
	return nil
}

func uniqueStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	seen := make(map[string]bool, len(values))
	out := values[:0]
	for _, value := range values {
		if seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return append([]string(nil), out...)
}

func uniqueSortedStrings(values []string) []string {
	out := uniqueStrings(values)
	sort.Strings(out)
	return out
}

func stringInSlice(value string, values []string) bool {
	for _, candidate := range values {
		if candidate == value {
			return true
		}
	}
	return false
}

func removeStrings(values, remove []string) []string {
	removeSet := make(map[string]bool, len(remove))
	for _, value := range remove {
		removeSet[value] = true
	}
	out := values[:0]
	for _, value := range values {
		if !removeSet[value] {
			out = append(out, value)
		}
	}
	if len(out) == 0 {
		return nil
	}
	return append([]string(nil), out...)
}

func findRuleset(rulesets []ruleset, name string) int {
	for i, rs := range rulesets {
		if rs.Name == name {
			return i
		}
	}
	return -1
}

func removeRuleset(rulesets []ruleset, name string) []ruleset {
	idx := findRuleset(rulesets, name)
	if idx < 0 {
		return append([]ruleset(nil), rulesets...)
	}
	out := append([]ruleset(nil), rulesets[:idx]...)
	out = append(out, rulesets[idx+1:]...)
	return out
}

func upsertRuleset(rulesets *[]ruleset, rs ruleset) {
	idx := findRuleset(*rulesets, rs.Name)
	if idx < 0 {
		*rulesets = append(*rulesets, rs)
	} else {
		(*rulesets)[idx] = rs
	}
	sortRulesets(*rulesets)
}

func sortRulesets(rulesets []ruleset) {
	sort.Slice(rulesets, func(i, j int) bool {
		return rulesets[i].Name < rulesets[j].Name
	})
}

func cloneOptions(opts options) options {
	out := opts
	out.InterfaceTypes = cloneStrings(opts.InterfaceTypes)
	out.InterfaceNames = cloneStrings(opts.InterfaceNames)
	out.InterfaceRegexps = cloneStrings(opts.InterfaceRegexps)
	out.IgnoredInterfaceTypes = cloneStrings(opts.IgnoredInterfaceTypes)
	out.IgnoredInterfaceNames = cloneStrings(opts.IgnoredInterfaceNames)
	out.IgnoredInterfaceRegexps = cloneStrings(opts.IgnoredInterfaceRegexps)
	out.allowRules = cloneAllowRules(opts.allowRules)
	out.Rulesets = make([]ruleset, len(opts.Rulesets))
	for i, rs := range opts.Rulesets {
		out.Rulesets[i] = ruleset{
			Name:       rs.Name,
			Disabled:   rs.Disabled,
			MatchAll:   rs.MatchAll,
			Trigger:    cloneRulesetTrigger(rs.Trigger),
			allowRules: cloneAllowRules(rs.allowRules),
		}
	}
	return out
}

func cloneRulesetTrigger(trigger rulesetTrigger) rulesetTrigger {
	return rulesetTrigger{
		InterfaceTypes:   cloneStrings(trigger.InterfaceTypes),
		InterfaceNames:   cloneStrings(trigger.InterfaceNames),
		InterfaceRegexps: cloneStrings(trigger.InterfaceRegexps),
		IPAddrs:          append([]netip.Addr(nil), trigger.IPAddrs...),
	}
}

func cloneAllowRules(rules allowRules) allowRules {
	return allowRules{
		AllowAll:       rules.AllowAll,
		EnableV4:       rules.EnableV4,
		EnableV6:       rules.EnableV6,
		AllowedMarks:   append([]uint32(nil), rules.AllowedMarks...),
		AllowedPorts:   append([]portKey(nil), rules.AllowedPorts...),
		AllowedV4Hosts: append([]uint32(nil), rules.AllowedV4Hosts...),
		AllowedV6Hosts: append([]ipv6AddrKey(nil), rules.AllowedV6Hosts...),
		AllowedV4Pairs: append([]hostport4Key(nil), rules.AllowedV4Pairs...),
		AllowedV6Pairs: append([]hostport6Key(nil), rules.AllowedV6Pairs...),
	}
}

func cloneTemporaryRulesets(rulesets map[string]temporaryRuleset) []temporaryRuleset {
	if len(rulesets) == 0 {
		return nil
	}
	owners := make([]string, 0, len(rulesets))
	for owner := range rulesets {
		owners = append(owners, owner)
	}
	sort.Strings(owners)

	out := make([]temporaryRuleset, 0, len(owners))
	for _, owner := range owners {
		tmp := rulesets[owner]
		out = append(out, temporaryRuleset{
			Owner:      owner,
			Interfaces: cloneStrings(tmp.Interfaces),
			Rules:      cloneAllowRules(tmp.Rules),
		})
	}
	return out
}

func cloneForceRulesets(rulesets map[string]map[string]map[string]int) []forceRuleset {
	if len(rulesets) == 0 {
		return nil
	}
	names := make([]string, 0, len(rulesets))
	for name := range rulesets {
		if len(rulesets[name]) > 0 {
			names = append(names, name)
		}
	}
	sort.Strings(names)

	out := make([]forceRuleset, 0, len(names))
	for _, name := range names {
		ownerSet := make(map[string]bool)
		ifaceSet := make(map[string]bool)
		for owner, ifaces := range rulesets[name] {
			ownerSet[owner] = true
			for iface := range ifaces {
				ifaceSet[iface] = true
			}
		}
		owners := make([]string, 0, len(ownerSet))
		for owner := range ownerSet {
			owners = append(owners, owner)
		}
		sort.Strings(owners)
		ifaces := make([]string, 0, len(ifaceSet))
		for iface := range ifaceSet {
			ifaces = append(ifaces, iface)
		}
		sort.Strings(ifaces)
		out = append(out, forceRuleset{
			Name:       name,
			Owners:     owners,
			Interfaces: ifaces,
		})
	}
	return out
}

func run(parent context.Context, opts options) error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock rlimit: %w", err)
	}

	var objs killswitchObjects
	if err := loadKillswitchObjects(&objs, nil); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}
	defer objs.Close() //nolint:errcheck

	manager := newEgressManager(objs.KillswitchEgress)
	defer manager.close()
	policies := newPolicyManager(&objs, opts)

	signalCtx, stop := signal.NotifyContext(parent, os.Interrupt, syscall.SIGTERM)
	defer stop()
	ctx, cancel := context.WithCancel(signalCtx)
	defer cancel()

	reader, err := ringbuf.NewReader(objs.BootstrapEvents)
	if err != nil {
		return fmt.Errorf("open bootstrap event ring buffer: %w", err)
	}
	defer reader.Close() //nolint:errcheck

	go func() {
		<-ctx.Done()
		_ = reader.Close()
	}()

	var reconcileMu sync.Mutex

	var adminServer *adminAPIServer
	notifyError := func(header string, err error) {
		if adminServer != nil {
			adminServer.notifyError(header, err)
		}
	}

	configSnapshot := func() adminapi.CurrentConfig {
		return currentConfigSnapshot(policies, manager, adminServer.clientSnapshot, notifyError)
	}
	adminServer = newAdminAPIServer(opts.AdminAPI, configSnapshot, func(req adminapi.MutationRequest) adminapi.MutationResult {
		return applyAdminMutation(req, policies, manager, &reconcileMu)
	})

	errCh := make(chan error, 3)
	go func() {
		if err := readBootstrapEvents(reader, notifyError); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errCh <- err
		}
	}()
	adminServer.setTemporaryRulesetCallbacks(
		func(owner string, req adminapi.MutationRequest) adminapi.MutationResult {
			return applyTemporaryRulesetMutation(owner, req, policies, manager, &reconcileMu)
		},
		func(owner string) adminapi.MutationResult {
			return removeTemporaryRuleset(owner, policies, manager, &reconcileMu)
		},
	)
	adminServer.setForceRulesetCallbacks(
		func(owner string, req adminapi.MutationRequest) adminapi.MutationResult {
			return applyForceRulesetMutation(owner, req, policies, manager, &reconcileMu)
		},
		func(owner string) adminapi.MutationResult {
			return removeForceRulesets(owner, policies, manager, &reconcileMu)
		},
	)
	go func() {
		if err := watchInterfaces(ctx, manager, policies, &reconcileMu, func(eventType adminapi.EventType) {
			adminServer.notify(eventType)
		}); err != nil {
			errCh <- err
		}
	}()
	go func() {
		if err := adminServer.listenAndServe(ctx); err != nil {
			errCh <- err
		}
	}()

	select {
	case <-ctx.Done():
		return nil
	case err := <-errCh:
		cancel()
		return err
	}
}

func selectedInterfaces(opts options) ([]interfaceInfo, error) {
	all, err := listInterfaces()
	if err != nil {
		return nil, fmt.Errorf("list interfaces: %w", err)
	}
	return selectInterfaces(all, opts)
}

func listInterfaces() ([]interfaceInfo, error) {
	links, err := netlink.LinkList()
	if err != nil {
		return nil, err
	}

	all := make([]interfaceInfo, 0, len(links))
	for _, l := range links {
		attrs := l.Attrs()
		if attrs == nil {
			continue
		}
		addrs, err := interfaceAddrs(l)
		if err != nil {
			return nil, err
		}
		all = append(all, interfaceInfo{
			Index: attrs.Index,
			Name:  attrs.Name,
			Type:  l.Type(),
			Addrs: addrs,
		})
	}
	return all, nil
}

func interfaceAddrs(link netlink.Link) ([]netip.Addr, error) {
	addrList, err := netlink.AddrList(link, netlink.FAMILY_ALL)
	if err != nil {
		attrs := link.Attrs()
		if attrs != nil {
			return nil, fmt.Errorf("list addresses for %s(index %d): %w", attrs.Name, attrs.Index, err)
		}
		return nil, fmt.Errorf("list addresses: %w", err)
	}

	addrs := make([]netip.Addr, 0, len(addrList))
	for _, addr := range addrList {
		parsed, ok := netipAddrFromIP(addr.IP)
		if ok {
			addrs = append(addrs, parsed)
		}
	}
	sort.Slice(addrs, func(i, j int) bool {
		return addrs[i].Less(addrs[j])
	})
	return addrs, nil
}

func netipAddrFromIP(ip net.IP) (netip.Addr, bool) {
	if v4 := ip.To4(); v4 != nil {
		addr, ok := netip.AddrFromSlice(v4)
		return addr.Unmap(), ok
	}
	if v6 := ip.To16(); v6 != nil {
		addr, ok := netip.AddrFromSlice(v6)
		return addr.Unmap(), ok
	}
	return netip.Addr{}, false
}

func selectInterfaces(all []interfaceInfo, opts options) ([]interfaceInfo, error) {
	var selected []interfaceInfo
	for _, iface := range all {
		matches, err := interfaceMatchesSelectors(iface, opts)
		if err != nil {
			return nil, err
		}
		if matches {
			selected = append(selected, iface)
		}
	}

	sort.Slice(selected, func(i, j int) bool {
		return selected[i].Name < selected[j].Name
	})
	return selected, nil
}

func newPolicyManager(objs *killswitchObjects, opts options) *policyManager {
	return &policyManager{objs: objs, opts: opts}
}

func (m *policyManager) optionsSnapshot() options {
	m.mu.Lock()
	defer m.mu.Unlock()
	return cloneOptions(m.opts)
}

func (m *policyManager) replaceOptions(opts options) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.opts = cloneOptions(opts)
	m.pruneForceRulesetsLocked()
}

func (m *policyManager) temporaryRulesetsSnapshot() []temporaryRuleset {
	m.mu.Lock()
	defer m.mu.Unlock()
	return cloneTemporaryRulesets(m.tmpRulesets)
}

func (m *policyManager) forceRulesetsSnapshot() []forceRuleset {
	m.mu.Lock()
	defer m.mu.Unlock()
	return cloneForceRulesets(m.forceRulesets)
}

func (m *policyManager) setTemporaryRuleset(owner string, interfaces []string, rules allowRules) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.tmpRulesets == nil {
		m.tmpRulesets = make(map[string]temporaryRuleset)
	}
	m.tmpRulesets[owner] = temporaryRuleset{Owner: owner, Interfaces: cloneStrings(interfaces), Rules: cloneAllowRules(rules)}
}

func (m *policyManager) removeTemporaryRuleset(owner string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.tmpRulesets[owner]; !ok {
		return false
	}
	delete(m.tmpRulesets, owner)
	return true
}

func (m *policyManager) forceActivateRuleset(owner, name string, interfaces []string, replace bool) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	if findRuleset(m.opts.Rulesets, name) < 0 {
		return false
	}
	if m.forceRulesets == nil {
		m.forceRulesets = make(map[string]map[string]map[string]int)
	}
	owners := m.forceRulesets[name]
	if owners == nil {
		owners = make(map[string]map[string]int)
		m.forceRulesets[name] = owners
	}
	if owners[owner] == nil {
		owners[owner] = make(map[string]int)
	}
	if replace {
		clear(owners[owner])
	}
	for _, iface := range interfaces {
		owners[owner][iface]++
	}
	return true
}

func (m *policyManager) releaseForceRuleset(owner, name string, interfaces []string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.releaseForceRulesetLocked(owner, name, interfaces)
}

func (m *policyManager) removeForceRulesets(owner string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	changed := false
	for name := range m.forceRulesets {
		if m.releaseAllForceRulesetLocked(owner, name) {
			changed = true
		}
	}
	return changed
}

func (m *policyManager) releaseForceRulesetLocked(owner, name string, interfaces []string) bool {
	owners := m.forceRulesets[name]
	if owners == nil || len(owners[owner]) == 0 {
		return false
	}
	if len(interfaces) == 0 {
		delete(owners, owner)
	} else {
		for _, iface := range interfaces {
			if owners[owner][iface] <= 1 {
				delete(owners[owner], iface)
			} else {
				owners[owner][iface]--
			}
		}
		if len(owners[owner]) == 0 {
			delete(owners, owner)
		}
	}
	if len(owners) == 0 {
		delete(m.forceRulesets, name)
	}
	return true
}

func (m *policyManager) releaseAllForceRulesetLocked(owner, name string) bool {
	owners := m.forceRulesets[name]
	if owners == nil || len(owners[owner]) == 0 {
		return false
	}
	delete(owners, owner)
	if len(owners) == 0 {
		delete(m.forceRulesets, name)
	}
	return true
}

func (m *policyManager) pruneForceRulesetsLocked() {
	if len(m.forceRulesets) == 0 {
		return
	}
	for name := range m.forceRulesets {
		if findRuleset(m.opts.Rulesets, name) < 0 {
			delete(m.forceRulesets, name)
		}
	}
}

func (m *policyManager) reconcileAttached(manager *egressManager, logChange bool) (bool, error) {
	if manager == nil {
		return m.reconcile(nil, logChange)
	}
	attached := manager.attachedIndexSnapshot()
	if len(attached) == 0 {
		return m.reconcile(nil, logChange)
	}
	all, err := listInterfaces()
	if err != nil {
		return false, fmt.Errorf("list interfaces: %w", err)
	}
	current := make([]interfaceInfo, 0, len(attached))
	for _, iface := range all {
		if attached[iface.Index] {
			current = append(current, iface)
		}
	}
	return m.reconcile(current, logChange)
}

func (m *policyManager) reconcile(all []interfaceInfo, logChange bool) (bool, error) {
	opts := m.optionsSnapshot()
	tmpRulesets := m.temporaryRulesetsSnapshot()
	forceRulesets := m.forceRulesetsSnapshot()
	selected, err := selectInterfaces(all, opts)
	if err != nil {
		return false, err
	}
	next := effectivePoliciesForInterfaces(selected, opts, tmpRulesets, forceRulesets)

	m.mu.Lock()
	defer m.mu.Unlock()
	if m.set && interfacePolicyRulesEqual(m.current, next) {
		m.current = cloneInterfacePolicyMap(next)
		return false, nil
	}

	if err := writeEffectivePolicies(m.objs, m.current, next); err != nil {
		return false, err
	}
	m.current = cloneInterfacePolicyMap(next)
	m.set = true
	if logChange {
		logPolicies(next)
	}
	return true, nil
}

func (m *policyManager) configSnapshot() adminapi.CurrentConfig {
	m.mu.Lock()
	current := cloneInterfacePolicyMap(m.current)
	set := m.set
	opts := cloneOptions(m.opts)
	tmpRulesets := cloneTemporaryRulesets(m.tmpRulesets)
	forceRulesets := cloneForceRulesets(m.forceRulesets)
	m.mu.Unlock()

	if !set {
		current = nil
	}
	return adminapi.CurrentConfig{
		InterfaceTypes:          cloneStrings(opts.InterfaceTypes),
		InterfaceNames:          cloneStrings(opts.InterfaceNames),
		InterfaceRegexps:        cloneStrings(opts.InterfaceRegexps),
		IgnoredInterfaceTypes:   cloneStrings(opts.IgnoredInterfaceTypes),
		IgnoredInterfaceNames:   cloneStrings(opts.IgnoredInterfaceNames),
		IgnoredInterfaceRegexps: cloneStrings(opts.IgnoredInterfaceRegexps),
		BasePolicy:              apiAllowRules(opts.allowRules),
		EffectivePolicy:         apiAllowRules(firstEffectivePolicy(current, opts.allowRules)),
		ActiveRuleset:           firstActiveRuleset(current),
		EffectiveInterfaces:     apiInterfacePolicies(current),
		Rulesets:                apiRulesets(opts.Rulesets, activeRulesetSet(current)),
		ForceActiveRulesets:     apiForceRulesets(forceRulesets),
		TemporaryRulesets:       apiTemporaryRulesets(tmpRulesets),
		AdminAPI: adminapi.AdminConfig{
			SocketPath: opts.AdminAPI.SocketPath,
			Debug:      opts.AdminAPI.Debug,
		},
	}
}

func currentConfigSnapshot(policies *policyManager, manager *egressManager, clients func() []adminapi.ClientInfo, notifyError func(string, error)) adminapi.CurrentConfig {
	cfg := policies.configSnapshot()
	opts := policies.optionsSnapshot()
	all, err := listInterfaces()
	if err != nil {
		log.Printf("ERROR: list interfaces for admin API snapshot: %s", err)
		if notifyError != nil {
			notifyError("Admin API snapshot error", err)
		}
	} else {
		cfg.Interfaces = apiInterfaces(all, opts, manager, notifyError)
	}
	if clients != nil {
		cfg.Clients = clients()
	}
	return cfg
}

type temporaryRuleset struct {
	Owner      string
	Interfaces []string
	Rules      allowRules
}

type forceRuleset struct {
	Name       string
	Owners     []string
	Interfaces []string
}

func effectiveAllowRules(base allowRules, active []ruleset, forceRulesets []ruleset, tmpRulesets []temporaryRuleset) allowRules {
	effective := base
	for _, ruleset := range active {
		effective = mergeAllowRules(effective, ruleset.allowRules)
	}
	for _, ruleset := range forceRulesets {
		effective = mergeAllowRules(effective, ruleset.allowRules)
	}
	for _, tmp := range tmpRulesets {
		effective = mergeAllowRules(effective, tmp.Rules)
	}
	return canonicalAllowRules(effective)
}

func forcedRulesetsForInterface(rulesets []ruleset, forceRulesets []forceRuleset, ifaceName string) []ruleset {
	if len(forceRulesets) == 0 {
		return nil
	}
	out := make([]ruleset, 0, len(forceRulesets))
	for _, forced := range forceRulesets {
		if !stringInSlice(ifaceName, forced.Interfaces) {
			continue
		}
		idx := findRuleset(rulesets, forced.Name)
		if idx >= 0 {
			out = append(out, rulesets[idx])
		}
	}
	return out
}

func temporaryRulesetsForInterface(rulesets []temporaryRuleset, ifaceName string) []temporaryRuleset {
	out := make([]temporaryRuleset, 0, len(rulesets))
	for _, ruleset := range rulesets {
		if stringInSlice(ifaceName, ruleset.Interfaces) {
			out = append(out, ruleset)
		}
	}
	return out
}

func effectivePoliciesForInterfaces(ifaces []interfaceInfo, opts options, tmpRulesets []temporaryRuleset, forceRulesets []forceRuleset) map[int]interfacePolicy {
	if len(ifaces) == 0 {
		return nil
	}
	out := make(map[int]interfacePolicy, len(ifaces))
	for _, iface := range ifaces {
		active := activeRulesetsForInterface(iface, opts.Rulesets)
		forced := forcedRulesetsForInterface(opts.Rulesets, forceRulesets, iface.Name)
		tmp := temporaryRulesetsForInterface(tmpRulesets, iface.Name)
		out[iface.Index] = interfacePolicy{
			Info:              iface,
			Rules:             effectiveAllowRules(opts.allowRules, active, forced, tmp),
			ActiveRulesets:    rulesetNames(active),
			ForcedRulesets:    rulesetNames(forced),
			TemporaryRulesets: temporaryRulesetOwners(tmp),
		}
	}
	return out
}

func activeRulesetsForInterface(iface interfaceInfo, rulesets []ruleset) []ruleset {
	out := make([]ruleset, 0, len(rulesets))
	for _, ruleset := range rulesets {
		if ruleset.Disabled {
			continue
		}
		if rulesetTriggerMatchesInterface(iface, ruleset.Trigger, ruleset.MatchAll) {
			out = append(out, ruleset)
		}
	}
	return out
}

func rulesetNames(rulesets []ruleset) []string {
	out := make([]string, 0, len(rulesets))
	for _, ruleset := range rulesets {
		out = append(out, ruleset.Name)
	}
	sort.Strings(out)
	return out
}

func temporaryRulesetOwners(rulesets []temporaryRuleset) []string {
	out := make([]string, 0, len(rulesets))
	for _, ruleset := range rulesets {
		out = append(out, ruleset.Owner)
	}
	sort.Strings(out)
	return out
}

func apiRulesets(rulesets []ruleset, activeNames map[string]bool) []adminapi.Ruleset {
	if len(rulesets) == 0 {
		return nil
	}
	out := make([]adminapi.Ruleset, 0, len(rulesets))
	for _, ruleset := range rulesets {
		out = append(out, adminapi.Ruleset{
			Name:     ruleset.Name,
			Active:   !ruleset.Disabled && activeNames[ruleset.Name],
			Disabled: ruleset.Disabled,
			MatchAll: ruleset.MatchAll,
			Trigger: adminapi.RulesetTrigger{
				InterfaceTypes:   cloneStrings(ruleset.Trigger.InterfaceTypes),
				InterfaceNames:   cloneStrings(ruleset.Trigger.InterfaceNames),
				InterfaceRegexps: cloneStrings(ruleset.Trigger.InterfaceRegexps),
				IPAddrs:          apiAddrs(ruleset.Trigger.IPAddrs),
			},
			Policy: apiAllowRules(ruleset.allowRules),
		})
	}
	return out
}

func apiTemporaryRulesets(rulesets []temporaryRuleset) []adminapi.TmpRuleset {
	if len(rulesets) == 0 {
		return nil
	}
	out := make([]adminapi.TmpRuleset, 0, len(rulesets))
	for _, ruleset := range rulesets {
		out = append(out, adminapi.TmpRuleset{
			Client:     ruleset.Owner,
			Interfaces: cloneStrings(ruleset.Interfaces),
			Policy:     apiAllowRules(ruleset.Rules),
		})
	}
	return out
}

func apiForceRulesets(rulesets []forceRuleset) []adminapi.ForceRuleset {
	if len(rulesets) == 0 {
		return nil
	}
	out := make([]adminapi.ForceRuleset, 0, len(rulesets))
	for _, ruleset := range rulesets {
		out = append(out, adminapi.ForceRuleset{
			Name:       ruleset.Name,
			Clients:    cloneStrings(ruleset.Owners),
			Interfaces: cloneStrings(ruleset.Interfaces),
		})
	}
	return out
}

func apiInterfacePolicies(current map[int]interfacePolicy) []adminapi.InterfacePolicy {
	if len(current) == 0 {
		return nil
	}
	indexes := make([]int, 0, len(current))
	for index := range current {
		indexes = append(indexes, index)
	}
	sort.Slice(indexes, func(i, j int) bool {
		a, b := current[indexes[i]].Info, current[indexes[j]].Info
		if a.Name != b.Name {
			return a.Name < b.Name
		}
		return a.Index < b.Index
	})
	out := make([]adminapi.InterfacePolicy, 0, len(indexes))
	for _, index := range indexes {
		p := current[index]
		out = append(out, adminapi.InterfacePolicy{
			Index:             p.Info.Index,
			Name:              p.Info.Name,
			Type:              p.Info.Type,
			Matched:           true,
			Attached:          true,
			EffectivePolicy:   apiAllowRules(p.Rules),
			ActiveRulesets:    cloneStrings(p.ActiveRulesets),
			ForcedRulesets:    cloneStrings(p.ForcedRulesets),
			TemporaryRulesets: cloneStrings(p.TemporaryRulesets),
		})
	}
	return out
}

func firstEffectivePolicy(current map[int]interfacePolicy, fallback allowRules) allowRules {
	for _, policy := range current {
		return policy.Rules
	}
	return fallback
}

func firstActiveRuleset(current map[int]interfacePolicy) string {
	for _, policy := range current {
		if len(policy.ActiveRulesets) > 0 {
			return policy.ActiveRulesets[0]
		}
	}
	return ""
}

func activeRulesetSet(current map[int]interfacePolicy) map[string]bool {
	out := make(map[string]bool)
	for _, policy := range current {
		for _, name := range policy.ActiveRulesets {
			out[name] = true
		}
	}
	return out
}

func apiAllowRules(rules allowRules) adminapi.AllowRules {
	return adminapi.AllowRules{
		AllowAll:       rules.AllowAll,
		EnableV4:       rules.EnableV4,
		EnableV6:       rules.EnableV6,
		AllowedMarks:   apiAllowedMarks(rules.AllowedMarks),
		AllowedPorts:   apiAllowedPorts(rules.AllowedPorts),
		AllowedV4Hosts: apiAllowedV4Hosts(rules.AllowedV4Hosts),
		AllowedV6Hosts: apiAllowedV6Hosts(rules.AllowedV6Hosts),
		AllowedV4Pairs: apiAllowedV4Pairs(rules.AllowedV4Pairs),
		AllowedV6Pairs: apiAllowedV6Pairs(rules.AllowedV6Pairs),
	}
}

func apiAllowedMarks(values []uint32) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, fmt.Sprintf("0x%x", value))
	}
	return out
}

func apiAllowedPorts(values []portKey) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, fmt.Sprintf("%s/%d", apiProtocol(value.Protocol), ntohs(value.Dport)))
	}
	return out
}

func apiAllowedV4Hosts(values []uint32) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, ipv4FromNetworkOrder(value).String())
	}
	return out
}

func apiAllowedV6Hosts(values []ipv6AddrKey) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, netip.AddrFrom16(value.Addr).String())
	}
	return out
}

func apiAllowedV4Pairs(values []hostport4Key) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, fmt.Sprintf("%s/%s:%d", apiProtocol(value.Protocol), ipv4FromNetworkOrder(value.Daddr), ntohs(value.Dport)))
	}
	return out
}

func apiAllowedV6Pairs(values []hostport6Key) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		addrPort := netip.AddrPortFrom(netip.AddrFrom16(value.Daddr), ntohs(value.Dport))
		out = append(out, fmt.Sprintf("%s/%s", apiProtocol(value.Protocol), addrPort))
	}
	return out
}

func apiProtocol(protocol uint8) string {
	switch protocol {
	case ipProtoTCP:
		return "tcp"
	case ipProtoUDP:
		return "udp"
	default:
		return fmt.Sprintf("proto%d", protocol)
	}
}

func apiAddrs(values []netip.Addr) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, value.String())
	}
	return out
}

func apiInterfaces(all []interfaceInfo, opts options, manager *egressManager, notifyError func(string, error)) []adminapi.Interface {
	if len(all) == 0 {
		return nil
	}
	attached := manager.attachedIndexSnapshot()
	out := make([]adminapi.Interface, 0, len(all))
	for _, iface := range all {
		matched, err := interfaceMatchesSelectors(iface, opts)
		if err != nil {
			log.Printf("ERROR: match interface %s(index %d) for admin API snapshot: %s", iface.Name, iface.Index, err)
			if notifyError != nil {
				notifyError("Admin API snapshot error", err)
			}
		}
		out = append(out, adminapi.Interface{
			Index:      iface.Index,
			Name:       iface.Name,
			Type:       iface.Type,
			Addrs:      apiAddrs(iface.Addrs),
			Matched:    matched,
			Killswitch: attached[iface.Index],
		})
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Name < out[j].Name
	})
	return out
}

func (m *egressManager) attachedIndexSnapshot() map[int]bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make(map[int]bool, len(m.attached))
	for index := range m.attached {
		out[index] = true
	}
	return out
}

func cloneStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	return append([]string(nil), values...)
}

func rulesetTriggerMatchesInterface(iface interfaceInfo, trigger rulesetTrigger, matchAll bool) bool {
	total := len(trigger.InterfaceTypes) + len(trigger.InterfaceNames) + len(trigger.InterfaceRegexps) + len(trigger.IPAddrs)
	if total == 0 {
		return false
	}

	matched := 0
	for _, typ := range trigger.InterfaceTypes {
		if iface.Type == typ {
			matched++
		}
	}
	for _, name := range trigger.InterfaceNames {
		if iface.Name == name {
			matched++
		}
	}
	for _, pattern := range trigger.InterfaceRegexps {
		if regexp.MustCompile(pattern).MatchString(iface.Name) {
			matched++
		}
	}
	for _, addr := range trigger.IPAddrs {
		for _, ifaceAddr := range iface.Addrs {
			if ifaceAddr.Unmap() == addr.Unmap() {
				matched++
				break
			}
		}
	}
	if matchAll {
		return matched == total
	}
	return matched > 0
}

func writeRuntimeConfig(m *ebpf.Map, ifindex uint32, config runtimeConfig) error {
	if err := m.Update(ifindex, config, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("update runtime_config map: %w", err)
	}
	return nil
}

func writeEffectivePolicies(objs *killswitchObjects, current, next map[int]interfacePolicy) error {
	if objs == nil {
		return nil
	}
	for index := range current {
		if _, ok := next[index]; !ok {
			if err := clearPolicyForInterface(objs, uint32(index)); err != nil {
				return err
			}
		}
	}
	for index, policy := range next {
		if currentPolicy, ok := current[index]; ok && allowRulesEqual(currentPolicy.Rules, policy.Rules) {
			continue
		}
		if err := writeEffectivePolicyForInterface(objs, uint32(index), policy.Rules); err != nil {
			return err
		}
	}
	return nil
}

func writeEffectivePolicyForInterface(objs *killswitchObjects, ifindex uint32, rules allowRules) error {
	if err := clearPolicyForInterface(objs, ifindex); err != nil {
		return err
	}
	if err := writeAllowlists(objs, ifindex, rules); err != nil {
		return err
	}
	if err := writeRuntimeConfig(objs.RuntimeConfig, ifindex, runtimeConfig{
		AllowAll: boolByte(rules.AllowAll),
		EnableV4: boolByte(rules.EnableV4),
		EnableV6: boolByte(rules.EnableV6),
	}); err != nil {
		return err
	}
	return nil
}

func clearPolicyForInterface(objs *killswitchObjects, ifindex uint32) error {
	if err := clearRuntimeConfig(objs.RuntimeConfig, ifindex); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[markPolicyKey](objs.AllowedMarks, "allowed_marks", ifindex, func(k markPolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[portPolicyKey](objs.AllowedPorts, "allowed_ports", ifindex, func(k portPolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[v4HostPolicyKey](objs.AllowedV4Hosts, "allowed_v4_hosts", ifindex, func(k v4HostPolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[v6HostPolicyKey](objs.AllowedV6Hosts, "allowed_v6_hosts", ifindex, func(k v6HostPolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[hostport4PolicyKey](objs.AllowedV4Hostports, "allowed_v4_hostports", ifindex, func(k hostport4PolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	if err := clearAllowedMapForInterface[hostport6PolicyKey](objs.AllowedV6Hostports, "allowed_v6_hostports", ifindex, func(k hostport6PolicyKey) uint32 { return k.Ifindex }); err != nil {
		return err
	}
	return nil
}

func clearRuntimeConfig(m *ebpf.Map, ifindex uint32) error {
	if err := m.Delete(ifindex); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
		return fmt.Errorf("delete runtime_config map entry: %w", err)
	}
	return nil
}

func clearAllowedMapForInterface[K comparable](m *ebpf.Map, name string, ifindex uint32, keyIfindex func(K) uint32) error {
	var key K
	var value uint8
	entries := m.Iterate()
	for entries.Next(&key, &value) {
		if keyIfindex(key) != ifindex {
			continue
		}
		if err := m.Delete(key); err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
			return fmt.Errorf("delete %s map entry: %w", name, err)
		}
	}
	if err := entries.Err(); err != nil {
		return fmt.Errorf("iterate %s map: %w", name, err)
	}
	return nil
}

func writeAllowlists(objs *killswitchObjects, ifindex uint32, rules allowRules) error {
	if err := writeAllowedMarks(objs.AllowedMarks, ifindex, rules.AllowedMarks); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedPorts, scopedPortKeys(ifindex, rules.AllowedPorts), "allowed_ports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hosts, scopedV4HostKeys(ifindex, rules.AllowedV4Hosts), "allowed_v4_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hosts, scopedV6HostKeys(ifindex, rules.AllowedV6Hosts), "allowed_v6_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hostports, scopedV4HostportKeys(ifindex, rules.AllowedV4Pairs), "allowed_v4_hostports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hostports, scopedV6HostportKeys(ifindex, rules.AllowedV6Pairs), "allowed_v6_hostports"); err != nil {
		return err
	}
	return nil
}

func writeAllowedMarks(m *ebpf.Map, ifindex uint32, marks []uint32) error {
	keys := make([]markPolicyKey, 0, len(marks))
	for _, mark := range marks {
		keys = append(keys, markPolicyKey{Ifindex: ifindex, Mark: mark})
	}
	return writeAllowedMap(m, keys, "allowed_marks")
}

func writeAllowedMap[K comparable](m *ebpf.Map, keys []K, name string) error {
	var allowed uint8 = 1
	for _, key := range keys {
		if err := m.Update(key, allowed, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("update %s map: %w", name, err)
		}
	}
	return nil
}

func scopedPortKeys(ifindex uint32, values []portKey) []portPolicyKey {
	out := make([]portPolicyKey, 0, len(values))
	for _, value := range values {
		out = append(out, portPolicyKey{Ifindex: ifindex, Dport: value.Dport, Protocol: value.Protocol})
	}
	return out
}

func scopedV4HostKeys(ifindex uint32, values []uint32) []v4HostPolicyKey {
	out := make([]v4HostPolicyKey, 0, len(values))
	for _, value := range values {
		out = append(out, v4HostPolicyKey{Ifindex: ifindex, Daddr: value})
	}
	return out
}

func scopedV6HostKeys(ifindex uint32, values []ipv6AddrKey) []v6HostPolicyKey {
	out := make([]v6HostPolicyKey, 0, len(values))
	for _, value := range values {
		out = append(out, v6HostPolicyKey{Ifindex: ifindex, Addr: value.Addr})
	}
	return out
}

func scopedV4HostportKeys(ifindex uint32, values []hostport4Key) []hostport4PolicyKey {
	out := make([]hostport4PolicyKey, 0, len(values))
	for _, value := range values {
		out = append(out, hostport4PolicyKey{
			Ifindex:  ifindex,
			Daddr:    value.Daddr,
			Dport:    value.Dport,
			Protocol: value.Protocol,
		})
	}
	return out
}

func scopedV6HostportKeys(ifindex uint32, values []hostport6Key) []hostport6PolicyKey {
	out := make([]hostport6PolicyKey, 0, len(values))
	for _, value := range values {
		out = append(out, hostport6PolicyKey{
			Ifindex:  ifindex,
			Daddr:    value.Daddr,
			Dport:    value.Dport,
			Protocol: value.Protocol,
		})
	}
	return out
}

func mergeAllowRules(base allowRules, overlay allowRules) allowRules {
	return canonicalAllowRules(allowRules{
		AllowAll:       base.AllowAll || overlay.AllowAll,
		EnableV4:       base.EnableV4 || overlay.EnableV4,
		EnableV6:       base.EnableV6 || overlay.EnableV6,
		AllowedMarks:   append(append([]uint32(nil), base.AllowedMarks...), overlay.AllowedMarks...),
		AllowedPorts:   append(append([]portKey(nil), base.AllowedPorts...), overlay.AllowedPorts...),
		AllowedV4Hosts: append(append([]uint32(nil), base.AllowedV4Hosts...), overlay.AllowedV4Hosts...),
		AllowedV6Hosts: append(append([]ipv6AddrKey(nil), base.AllowedV6Hosts...), overlay.AllowedV6Hosts...),
		AllowedV4Pairs: append(append([]hostport4Key(nil), base.AllowedV4Pairs...), overlay.AllowedV4Pairs...),
		AllowedV6Pairs: append(append([]hostport6Key(nil), base.AllowedV6Pairs...), overlay.AllowedV6Pairs...),
	})
}

func canonicalAllowRules(rules allowRules) allowRules {
	rules.AllowedMarks = uniqueSorted(rules.AllowedMarks, func(a, b uint32) bool { return a < b })
	rules.AllowedPorts = uniqueSorted(rules.AllowedPorts, func(a, b portKey) bool {
		if a.Protocol != b.Protocol {
			return a.Protocol < b.Protocol
		}
		return a.Dport < b.Dport
	})
	rules.AllowedV4Hosts = uniqueSorted(rules.AllowedV4Hosts, func(a, b uint32) bool { return a < b })
	rules.AllowedV6Hosts = uniqueSorted(rules.AllowedV6Hosts, func(a, b ipv6AddrKey) bool {
		return bytes.Compare(a.Addr[:], b.Addr[:]) < 0
	})
	rules.AllowedV4Pairs = uniqueSorted(rules.AllowedV4Pairs, func(a, b hostport4Key) bool {
		if a.Protocol != b.Protocol {
			return a.Protocol < b.Protocol
		}
		if a.Daddr != b.Daddr {
			return a.Daddr < b.Daddr
		}
		return a.Dport < b.Dport
	})
	rules.AllowedV6Pairs = uniqueSorted(rules.AllowedV6Pairs, func(a, b hostport6Key) bool {
		if a.Protocol != b.Protocol {
			return a.Protocol < b.Protocol
		}
		if cmp := bytes.Compare(a.Daddr[:], b.Daddr[:]); cmp != 0 {
			return cmp < 0
		}
		return a.Dport < b.Dport
	})
	return rules
}

func uniqueSorted[K comparable](values []K, less func(a, b K) bool) []K {
	if len(values) == 0 {
		return nil
	}
	values = append([]K(nil), values...)
	sort.Slice(values, func(i, j int) bool {
		return less(values[i], values[j])
	})
	out := values[:0]
	for _, value := range values {
		if len(out) == 0 || out[len(out)-1] != value {
			out = append(out, value)
		}
	}
	return out
}

func allowRulesEqual(a, b allowRules) bool {
	return reflect.DeepEqual(canonicalAllowRules(a), canonicalAllowRules(b))
}

func interfacePolicyRulesEqual(a, b map[int]interfacePolicy) bool {
	if len(a) != len(b) {
		return false
	}
	for index, aPolicy := range a {
		bPolicy, ok := b[index]
		if !ok {
			return false
		}
		if aPolicy.Info.Name != bPolicy.Info.Name || aPolicy.Info.Type != bPolicy.Info.Type || !reflect.DeepEqual(aPolicy.Info.Addrs, bPolicy.Info.Addrs) {
			return false
		}
		if !allowRulesEqual(aPolicy.Rules, bPolicy.Rules) {
			return false
		}
	}
	return true
}

func cloneInterfacePolicyMap(values map[int]interfacePolicy) map[int]interfacePolicy {
	if len(values) == 0 {
		return nil
	}
	out := make(map[int]interfacePolicy, len(values))
	for index, value := range values {
		value.Info.Addrs = append([]netip.Addr(nil), value.Info.Addrs...)
		value.Rules = cloneAllowRules(value.Rules)
		value.ActiveRulesets = cloneStrings(value.ActiveRulesets)
		value.ForcedRulesets = cloneStrings(value.ForcedRulesets)
		value.TemporaryRulesets = cloneStrings(value.TemporaryRulesets)
		out[index] = value
	}
	return out
}

func logPolicies(policies map[int]interfacePolicy) {
	if len(policies) == 0 {
		log.Print("Effective policies: none")
		return
	}
	for _, policy := range sortedInterfacePolicies(policies) {
		logPolicy(policy)
	}
}

func sortedInterfacePolicies(policies map[int]interfacePolicy) []interfacePolicy {
	out := make([]interfacePolicy, 0, len(policies))
	for _, policy := range policies {
		out = append(out, policy)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Info.Name != out[j].Info.Name {
			return out[i].Info.Name < out[j].Info.Name
		}
		return out[i].Info.Index < out[j].Info.Index
	})
	return out
}

func logPolicy(policy interfacePolicy) {
	rules := policy.Rules
	if rules.AllowAll {
		log.Printf("WARNING: AllowAll is enabled on %s(index %d); protected interface will pass all traffic", policy.Info.Name, policy.Info.Index)
	}
	log.Printf("Effective policy for %s(index %d): active_rulesets=%s forced_rulesets=%s temporary_rulesets=%d allow_all=%t enable_v4=%t enable_v6=%t allowlists marks=%d ports=%d v4_hosts=%d v6_hosts=%d v4_hostports=%d v6_hostports=%d",
		policy.Info.Name,
		policy.Info.Index,
		strings.Join(policy.ActiveRulesets, ","),
		strings.Join(policy.ForcedRulesets, ","),
		len(policy.TemporaryRulesets),
		rules.AllowAll,
		rules.EnableV4,
		rules.EnableV6,
		len(rules.AllowedMarks),
		len(rules.AllowedPorts),
		len(rules.AllowedV4Hosts),
		len(rules.AllowedV6Hosts),
		len(rules.AllowedV4Pairs),
		len(rules.AllowedV6Pairs),
	)
}

func allowedPortKeys(values []string) ([]portKey, error) {
	rules, err := policy.ParseAllowedPorts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]portKey, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, portKey{Dport: htons(rule.Port), Protocol: rule.Protocol})
	}
	return keys, nil
}

func allowedV4HostKeys(values []string) ([]uint32, error) {
	addrs, err := policy.ParseAllowedV4Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]uint32, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv4Key(addr))
	}
	return keys, nil
}

func allowedV6HostKeys(values []string) ([]ipv6AddrKey, error) {
	addrs, err := policy.ParseAllowedV6Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]ipv6AddrKey, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv6Key(addr))
	}
	return keys, nil
}

func allowedV4HostportKeys(values []string) ([]hostport4Key, error) {
	rules, err := policy.ParseAllowedV4Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport4Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport4Key{
			Daddr:    ipv4Key(rule.AddrPort.Addr()),
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func allowedV6HostportKeys(values []string) ([]hostport6Key, error) {
	rules, err := policy.ParseAllowedV6Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport6Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport6Key{
			Daddr:    ipv6Key(rule.AddrPort.Addr()).Addr,
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func readBootstrapEvents(reader *ringbuf.Reader, notifyError func(string, error)) error {
	for {
		record, err := reader.Read()
		if err != nil {
			return err
		}

		event, err := parseBootstrapEvent(record.RawSample)
		if err != nil {
			log.Printf("parse bootstrap event: %s", err)
			if notifyError != nil {
				notifyError("Bootstrap event parse error", err)
			}
			continue
		}
		log.Print(formatBootstrapEvent(event))
	}
}

func parseBootstrapEvent(raw []byte) (bootstrapEvent, error) {
	var event bootstrapEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &event); err != nil {
		return bootstrapEvent{}, err
	}
	return event, nil
}

func formatBootstrapEvent(event bootstrapEvent) string {
	reason := "unknown"
	switch event.Reason {
	case bootstrapARP:
		reason = "arp"
	case bootstrapDHCPv4:
		reason = "dhcpv4"
	case bootstrapDHCPv6:
		reason = "dhcpv6"
	case bootstrapICMPv6:
		reason = "icmpv6_nd"
	}

	if event.Reason == bootstrapDHCPv4 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s:%d dst=%s:%d",
			reason,
			event.Ifindex,
			ipv4FromNetworkOrder(event.IPv4Saddr),
			ntohs(event.SourcePort),
			ipv4FromNetworkOrder(event.IPv4Daddr),
			ntohs(event.DestPort),
		)
	}
	if event.Reason == bootstrapDHCPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=[%s]:%d dst=[%s]:%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			ntohs(event.SourcePort),
			net.IP(event.IPv6Daddr[:]),
			ntohs(event.DestPort),
			event.VLANDepth,
		)
	}
	if event.Reason == bootstrapICMPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s dst=%s type=%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			net.IP(event.IPv6Daddr[:]),
			event.ICMPv6Type,
			event.VLANDepth,
		)
	}

	return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d eth_proto=0x%04x vlan_depth=%d",
		reason,
		event.Ifindex,
		event.EthProto,
		event.VLANDepth,
	)
}

func newEgressManager(program *ebpf.Program) *egressManager {
	return &egressManager{
		program:  program,
		attached: make(map[int]attachedInterface),
	}
}

func (m *egressManager) reconcileCurrent(opts options, strict bool) (bool, error) {
	selected, err := selectedInterfaces(opts)
	if err != nil {
		return false, err
	}
	if len(selected) == 0 {
		log.Print("No interfaces currently match the configured selectors")
	}
	return m.reconcile(selected, strict)
}

func (m *egressManager) reconcile(selected []interfaceInfo, strict bool) (bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	desired := make(map[int]interfaceInfo, len(selected))
	for _, iface := range selected {
		desired[iface.Index] = iface
	}

	changed := false
	for index, attached := range m.attached {
		if _, ok := desired[index]; ok {
			continue
		}
		if err := attached.link.Close(); err != nil {
			log.Printf("ERROR: detach tc egress program from %s(index %d type %s): %s", attached.info.Name, attached.info.Index, attached.info.Type, err)
		} else {
			log.Printf("Detached tc egress program from %s(index %d type %s)", attached.info.Name, attached.info.Index, attached.info.Type)
		}
		delete(m.attached, index)
		changed = true
	}

	var attachErr error
	for _, iface := range selected {
		if attached, ok := m.attached[iface.Index]; ok {
			attached.info = iface
			m.attached[iface.Index] = attached
			continue
		}

		l, err := link.AttachTCX(link.TCXOptions{
			Interface: iface.Index,
			Program:   m.program,
			Attach:    ebpf.AttachTCXEgress,
		})
		if err != nil {
			err = fmt.Errorf("attach tc egress program to %s(index %d type %s): %w", iface.Name, iface.Index, iface.Type, err)
			log.Printf("ERROR: %s", err)
			attachErr = errors.Join(attachErr, err)
			continue
		}
		m.attached[iface.Index] = attachedInterface{link: l, info: iface}
		log.Printf("Attached tc egress program to %s(index %d type %s)", iface.Name, iface.Index, iface.Type)
		changed = true
	}

	if changed {
		log.Printf("Kill switch attached to: %s", interfaceNames(m.attachedInterfacesLocked()))
	}
	if strict {
		return changed, attachErr
	}
	return changed, nil
}

func (m *egressManager) attachedInterfacesLocked() []interfaceInfo {
	ifaces := make([]interfaceInfo, 0, len(m.attached))
	for _, attached := range m.attached {
		ifaces = append(ifaces, attached.info)
	}
	sort.Slice(ifaces, func(i, j int) bool {
		return ifaces[i].Name < ifaces[j].Name
	})
	return ifaces
}

func (m *egressManager) close() {
	m.mu.Lock()
	defer m.mu.Unlock()
	for index, attached := range m.attached {
		if err := attached.link.Close(); err != nil {
			log.Printf("closing link for %s(index %d): %s", attached.info.Name, attached.info.Index, err)
		}
		delete(m.attached, index)
	}
}

func watchInterfaces(ctx context.Context, manager *egressManager, policies *policyManager, reconcileMu *sync.Mutex, notify func(adminapi.EventType)) error {
	linkUpdates := make(chan netlink.LinkUpdate, 32)
	addrUpdates := make(chan netlink.AddrUpdate, 32)
	done := make(chan struct{})
	defer close(done)

	subscribeErrs := make(chan error, 1)
	errCallback := func(err error) {
		select {
		case subscribeErrs <- err:
		default:
			log.Printf("ERROR: netlink link watcher: %s", err)
		}
	}

	if err := netlink.LinkSubscribeWithOptions(linkUpdates, done, netlink.LinkSubscribeOptions{
		ErrorCallback: errCallback,
	}); err != nil {
		return fmt.Errorf("subscribe to netlink link updates: %w", err)
	}
	if err := netlink.AddrSubscribeWithOptions(addrUpdates, done, netlink.AddrSubscribeOptions{
		ErrorCallback: errCallback,
	}); err != nil {
		return fmt.Errorf("subscribe to netlink addr updates: %w", err)
	}

	if _, err := manager.reconcileCurrent(policies.optionsSnapshot(), true); err != nil {
		return err
	}
	policyChanged, err := policies.reconcileAttached(manager, true)
	if err != nil {
		return err
	}
	if notify != nil {
		notify(adminapi.EventTypeInterfaces)
		if policyChanged {
			notify(adminapi.EventTypeConfig)
		}
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case err := <-subscribeErrs:
			return fmt.Errorf("netlink link watcher: %w", err)
		case update := <-linkUpdates:
			reconcileMu.Lock()
			opts := policies.optionsSnapshot()
			shouldReconcileAttachments := manager.shouldReconcileLinkUpdate(update, opts)
			interfacesChanged := false
			if shouldReconcileAttachments {
				var err error
				interfacesChanged, err = manager.reconcileCurrent(opts, false)
				if err != nil {
					log.Printf("ERROR: reconcile interfaces after netlink update: %s", err)
				}
			}
			policyChanged, err := policies.reconcileAttached(manager, true)
			if err != nil {
				log.Printf("ERROR: reconcile rulesets after netlink link update: %s", err)
			}
			reconcileMu.Unlock()
			if notify != nil {
				if interfacesChanged {
					notify(adminapi.EventTypeInterfaces)
				}
				if policyChanged {
					notify(adminapi.EventTypeConfig)
				}
			}
		case <-addrUpdates:
			reconcileMu.Lock()
			policyChanged, err := policies.reconcileAttached(manager, true)
			if err != nil {
				log.Printf("ERROR: reconcile rulesets after netlink addr update: %s", err)
			}
			reconcileMu.Unlock()
			if notify != nil {
				if policyChanged {
					notify(adminapi.EventTypeInterfaces)
					notify(adminapi.EventTypeConfig)
				}
			}
		}
	}
}

func (m *egressManager) shouldReconcileLinkUpdate(update netlink.LinkUpdate, opts options) bool {
	if update.Link == nil || update.Link.Attrs() == nil { //nolint:staticcheck
		return true
	}

	attrs := update.Link.Attrs() //nolint:staticcheck
	switch update.Header.Type {
	case unix.RTM_DELLINK:
		return m.isAttached(attrs.Index)
	case unix.RTM_NEWLINK:
		matches, err := interfaceMatchesSelectors(interfaceInfo{
			Index: attrs.Index,
			Name:  attrs.Name,
			Type:  update.Link.Type(), //nolint:staticcheck
		}, opts)
		if err != nil {
			log.Printf("ERROR: match netlink link update selectors: %s", err)
			return true
		}
		return matches != m.isAttached(attrs.Index)
	default:
		return false
	}
}

func (m *egressManager) isAttached(index int) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	_, ok := m.attached[index]
	return ok
}

func interfaceMatchesSelectors(iface interfaceInfo, opts options) (bool, error) {
	ignored, err := interfaceMatchesIgnoreSelectors(iface, opts)
	if err != nil {
		return false, err
	}
	if ignored {
		return false, nil
	}

	for _, typ := range opts.InterfaceTypes {
		if iface.Type == typ {
			return true, nil
		}
	}
	for _, name := range opts.InterfaceNames {
		if iface.Name == name {
			return true, nil
		}
	}
	for _, pattern := range opts.InterfaceRegexps {
		matches, err := regexp.MatchString(pattern, iface.Name)
		if err != nil {
			return false, fmt.Errorf("compile interface regexp %q: %w", pattern, err)
		}
		if matches {
			return true, nil
		}
	}
	return false, nil
}

func interfaceMatchesIgnoreSelectors(iface interfaceInfo, opts options) (bool, error) {
	if iface.Name == "lo" {
		return true, nil
	}
	for _, typ := range opts.IgnoredInterfaceTypes {
		if iface.Type == typ {
			return true, nil
		}
	}
	for _, name := range opts.IgnoredInterfaceNames {
		if iface.Name == name {
			return true, nil
		}
	}
	for _, pattern := range opts.IgnoredInterfaceRegexps {
		matches, err := regexp.MatchString(pattern, iface.Name)
		if err != nil {
			return false, fmt.Errorf("compile ignored interface regexp %q: %w", pattern, err)
		}
		if matches {
			return true, nil
		}
	}
	return false, nil
}

func interfaceNames(ifaces []interfaceInfo) string {
	names := make([]string, 0, len(ifaces))
	for _, iface := range ifaces {
		names = append(names, iface.Name)
	}
	return strings.Join(names, ", ")
}

func boolByte(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

func ntohs(value uint16) uint16 {
	return value<<8 | value>>8
}

func htons(value uint16) uint16 {
	return ntohs(value)
}

func ipv4FromNetworkOrder(value uint32) net.IP {
	return net.IPv4(byte(value), byte(value>>8), byte(value>>16), byte(value>>24))
}

func ipv4Key(addr netip.Addr) uint32 {
	octets := addr.As4()
	return binary.LittleEndian.Uint32(octets[:])
}

func ipv6Key(addr netip.Addr) ipv6AddrKey {
	var key ipv6AddrKey
	octets := addr.As16()
	copy(key.Addr[:], octets[:])
	return key
}
