//go:build linux

package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"net/netip"
	"os"
	"os/signal"
	"regexp"
	"sort"
	"strings"
	"syscall"

	"github.com/asciimoth/killswitch/internal/policy"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

const (
	bootstrapARP    = 1
	bootstrapDHCPv4 = 2
	bootstrapDHCPv6 = 3
	bootstrapICMPv6 = 4

	ipProtoTCP = policy.IPProtoTCP
	ipProtoUDP = policy.IPProtoUDP
)

// runtimeConfig mirrors struct runtime_config in killswitch.c. Keep this type
// byte-sized so map updates are ABI-stable across Go and C.
type runtimeConfig struct {
	AllowAll uint8
	EnableV4 uint8
	EnableV6 uint8
	Reserved uint8
}

// bootstrapEvent mirrors struct bootstrap_event in killswitch.c. The eBPF
// program emits only bootstrap pass events so this channel remains low volume.
type bootstrapEvent struct {
	TimestampNS uint64
	Ifindex     uint32
	EthProto    uint16
	Reason      uint8
	IPProto     uint8
	IPv4Saddr   uint32
	IPv4Daddr   uint32
	IPv6Saddr   [16]byte
	IPv6Daddr   [16]byte
	SourcePort  uint16
	DestPort    uint16
	ICMPv6Type  uint8
	VLANDepth   uint8
	Reserved    uint16
}

// portKey mirrors struct port_key in killswitch.c. Ports are stored in network
// byte order because the eBPF parser compares them directly with packet fields.
type portKey struct {
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

// ipv6AddrKey mirrors struct ipv6_addr_key in killswitch.c.
type ipv6AddrKey struct {
	Addr [16]byte
}

// hostport4Key mirrors struct hostport4_key in killswitch.c. Explicit padding
// keeps the Go value layout aligned with the C map key ABI generated by clang.
type hostport4Key struct {
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

// hostport6Key mirrors struct hostport6_key in killswitch.c.
type hostport6Key struct {
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type stringList []string

func (s *stringList) String() string {
	return strings.Join(*s, ",")
}

func (s *stringList) Set(value string) error {
	if value == "" {
		return errors.New("empty value")
	}
	*s = append(*s, value)
	return nil
}

type options struct {
	InterfaceNames   []string
	InterfaceRegexps []string
	AllowAll         bool
	EnableV4         bool
	EnableV6         bool
	AllowedMarks     []uint32
	AllowedPorts     []portKey
	AllowedV4Hosts   []uint32
	AllowedV6Hosts   []ipv6AddrKey
	AllowedV4Pairs   []hostport4Key
	AllowedV6Pairs   []hostport6Key
}

func main() {
	opts, err := parseFlags(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}

	if err := run(context.Background(), opts); err != nil {
		log.Fatal(err)
	}
}

func parseFlags(args []string) (options, error) {
	var ifaces stringList
	var ifaceRegexps stringList
	var allowMarks stringList
	var allowPorts stringList
	var allowV4Hosts stringList
	var allowV6Hosts stringList
	var allowV4Hostports stringList
	var allowV6Hostports stringList
	opts := options{}

	fs := flag.NewFlagSet("killswitch", flag.ContinueOnError)
	fs.Var(&ifaces, "iface", "interface name to protect; may be repeated")
	fs.Var(&ifaceRegexps, "iface-regex", "regular expression selecting interface names to protect; may be repeated")
	fs.BoolVar(&opts.AllowAll, "allow-all", false, "pass all traffic before parsing; disables enforcement")
	fs.BoolVar(&opts.EnableV4, "enable-v4", false, "enable IPv4 gate; traffic still drops until later allowlist phases")
	fs.BoolVar(&opts.EnableV6, "enable-v6", false, "enable IPv6 gate; traffic still drops until later allowlist phases")
	fs.Var(&allowMarks, "allow-mark", "allow packets with skb mark value; decimal or 0x-prefixed; may be repeated")
	fs.Var(&allowPorts, "allow-port", "allow TCP/UDP destination port globally as tcp/443 or udp/51820; may be repeated")
	fs.Var(&allowV4Hosts, "allow-v4-host", "allow IPv4 destination host; may be repeated")
	fs.Var(&allowV6Hosts, "allow-v6-host", "allow IPv6 destination host; may be repeated")
	fs.Var(&allowV4Hostports, "allow-v4-hostport", "allow IPv4 destination host and port as tcp/192.0.2.1:443; may be repeated")
	fs.Var(&allowV6Hostports, "allow-v6-hostport", "allow IPv6 destination host and port as udp/[2001:db8::1]:51820; may be repeated")
	fs.SetOutput(os.Stderr)

	if err := fs.Parse(args); err != nil {
		return options{}, err
	}
	if fs.NArg() != 0 {
		return options{}, fmt.Errorf("unexpected positional arguments: %s", strings.Join(fs.Args(), " "))
	}

	opts.InterfaceNames = ifaces
	opts.InterfaceRegexps = ifaceRegexps
	if len(opts.InterfaceNames) == 0 && len(opts.InterfaceRegexps) == 0 {
		return options{}, errors.New("at least one -iface or -iface-regex is required")
	}

	for _, pattern := range opts.InterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return options{}, fmt.Errorf("compile -iface-regex %q: %w", pattern, err)
		}
	}
	var err error
	if opts.AllowedMarks, err = policy.ParseAllowedMarks(allowMarks); err != nil {
		return options{}, err
	}
	if opts.AllowedPorts, err = allowedPortKeys(allowPorts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Hosts, err = allowedV4HostKeys(allowV4Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Hosts, err = allowedV6HostKeys(allowV6Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Pairs, err = allowedV4HostportKeys(allowV4Hostports); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Pairs, err = allowedV6HostportKeys(allowV6Hostports); err != nil {
		return options{}, err
	}

	return opts, nil
}

func run(parent context.Context, opts options) error {
	if opts.AllowAll {
		log.Print("WARNING: AllowAll is enabled; protected interfaces will pass all traffic")
	}

	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock rlimit: %w", err)
	}

	var objs killswitchObjects
	if err := loadKillswitchObjects(&objs, nil); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}
	defer objs.Close() //nolint:errcheck

	if err := writeRuntimeConfig(objs.RuntimeConfig, runtimeConfig{
		AllowAll: boolByte(opts.AllowAll),
		EnableV4: boolByte(opts.EnableV4),
		EnableV6: boolByte(opts.EnableV6),
	}); err != nil {
		return err
	}
	if err := writeAllowlists(&objs, opts); err != nil {
		return err
	}

	ifaces, err := selectedInterfaces(opts)
	if err != nil {
		return err
	}
	if len(ifaces) == 0 {
		return errors.New("no interfaces matched the configured selectors")
	}

	links, err := attachEgress(objs.KillswitchEgress, ifaces)
	if err != nil {
		return err
	}
	defer closeLinks(links)

	ctx, stop := signal.NotifyContext(parent, os.Interrupt, syscall.SIGTERM)
	defer stop()

	reader, err := ringbuf.NewReader(objs.BootstrapEvents)
	if err != nil {
		return fmt.Errorf("open bootstrap event ring buffer: %w", err)
	}
	defer reader.Close() //nolint:errcheck

	go func() {
		<-ctx.Done()
		_ = reader.Close()
	}()

	log.Printf("Kill switch attached to: %s", interfaceNames(ifaces))
	log.Printf("Runtime config: allow_all=%t enable_v4=%t enable_v6=%t", opts.AllowAll, opts.EnableV4, opts.EnableV6)
	log.Printf("Allowlists: marks=%d ports=%d v4_hosts=%d v6_hosts=%d v4_hostports=%d v6_hostports=%d",
		len(opts.AllowedMarks),
		len(opts.AllowedPorts),
		len(opts.AllowedV4Hosts),
		len(opts.AllowedV6Hosts),
		len(opts.AllowedV4Pairs),
		len(opts.AllowedV6Pairs),
	)

	if err := readBootstrapEvents(reader); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
		return err
	}
	return nil
}

func selectedInterfaces(opts options) ([]net.Interface, error) {
	all, err := net.Interfaces()
	if err != nil {
		return nil, fmt.Errorf("list interfaces: %w", err)
	}
	return selectInterfaces(all, opts)
}

func selectInterfaces(all []net.Interface, opts options) ([]net.Interface, error) {
	names := make(map[string]struct{}, len(opts.InterfaceNames))
	for _, name := range opts.InterfaceNames {
		names[name] = struct{}{}
	}

	regexps := make([]*regexp.Regexp, 0, len(opts.InterfaceRegexps))
	for _, pattern := range opts.InterfaceRegexps {
		re, err := regexp.Compile(pattern)
		if err != nil {
			return nil, fmt.Errorf("compile interface regexp %q: %w", pattern, err)
		}
		regexps = append(regexps, re)
	}

	var selected []net.Interface
	for _, iface := range all {
		if _, ok := names[iface.Name]; ok {
			selected = append(selected, iface)
			continue
		}
		for _, re := range regexps {
			if re.MatchString(iface.Name) {
				selected = append(selected, iface)
				break
			}
		}
	}

	sort.Slice(selected, func(i, j int) bool {
		return selected[i].Name < selected[j].Name
	})
	return selected, nil
}

func writeRuntimeConfig(m *ebpf.Map, config runtimeConfig) error {
	var key uint32
	if err := m.Update(key, config, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("update runtime_config map: %w", err)
	}
	return nil
}

func writeAllowlists(objs *killswitchObjects, opts options) error {
	if err := writeAllowedMarks(objs.AllowedMarks, opts.AllowedMarks); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedPorts, opts.AllowedPorts, "allowed_ports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hosts, opts.AllowedV4Hosts, "allowed_v4_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hosts, opts.AllowedV6Hosts, "allowed_v6_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hostports, opts.AllowedV4Pairs, "allowed_v4_hostports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hostports, opts.AllowedV6Pairs, "allowed_v6_hostports"); err != nil {
		return err
	}
	return nil
}

func writeAllowedMarks(m *ebpf.Map, marks []uint32) error {
	return writeAllowedMap(m, marks, "allowed_marks")
}

func writeAllowedMap[K comparable](m *ebpf.Map, keys []K, name string) error {
	var allowed uint8 = 1
	for _, key := range keys {
		if err := m.Update(key, allowed, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("update %s map: %w", name, err)
		}
	}
	return nil
}

func attachEgress(program *ebpf.Program, ifaces []net.Interface) ([]link.Link, error) {
	links := make([]link.Link, 0, len(ifaces))
	for _, iface := range ifaces {
		l, err := link.AttachTCX(link.TCXOptions{
			Interface: iface.Index,
			Program:   program,
			Attach:    ebpf.AttachTCXEgress,
		})
		if err != nil {
			closeLinks(links)
			return nil, fmt.Errorf("attach tc egress program to %s(index %d): %w", iface.Name, iface.Index, err)
		}
		log.Printf("Attached tc egress program to %s(index %d)", iface.Name, iface.Index)
		links = append(links, l)
	}
	return links, nil
}

func allowedPortKeys(values []string) ([]portKey, error) {
	rules, err := policy.ParseAllowedPorts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]portKey, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, portKey{Dport: htons(rule.Port), Protocol: rule.Protocol})
	}
	return keys, nil
}

func allowedV4HostKeys(values []string) ([]uint32, error) {
	addrs, err := policy.ParseAllowedV4Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]uint32, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv4Key(addr))
	}
	return keys, nil
}

func allowedV6HostKeys(values []string) ([]ipv6AddrKey, error) {
	addrs, err := policy.ParseAllowedV6Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]ipv6AddrKey, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv6Key(addr))
	}
	return keys, nil
}

func allowedV4HostportKeys(values []string) ([]hostport4Key, error) {
	rules, err := policy.ParseAllowedV4Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport4Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport4Key{
			Daddr:    ipv4Key(rule.AddrPort.Addr()),
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func allowedV6HostportKeys(values []string) ([]hostport6Key, error) {
	rules, err := policy.ParseAllowedV6Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport6Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport6Key{
			Daddr:    ipv6Key(rule.AddrPort.Addr()).Addr,
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func closeLinks(links []link.Link) {
	for _, l := range links {
		if err := l.Close(); err != nil {
			log.Printf("closing link: %s", err)
		}
	}
}

func readBootstrapEvents(reader *ringbuf.Reader) error {
	for {
		record, err := reader.Read()
		if err != nil {
			return err
		}

		event, err := parseBootstrapEvent(record.RawSample)
		if err != nil {
			log.Printf("parse bootstrap event: %s", err)
			continue
		}
		log.Print(formatBootstrapEvent(event))
	}
}

func parseBootstrapEvent(raw []byte) (bootstrapEvent, error) {
	var event bootstrapEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &event); err != nil {
		return bootstrapEvent{}, err
	}
	return event, nil
}

func formatBootstrapEvent(event bootstrapEvent) string {
	reason := "unknown"
	switch event.Reason {
	case bootstrapARP:
		reason = "arp"
	case bootstrapDHCPv4:
		reason = "dhcpv4"
	case bootstrapDHCPv6:
		reason = "dhcpv6"
	case bootstrapICMPv6:
		reason = "icmpv6_nd"
	}

	if event.Reason == bootstrapDHCPv4 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s:%d dst=%s:%d",
			reason,
			event.Ifindex,
			ipv4FromNetworkOrder(event.IPv4Saddr),
			ntohs(event.SourcePort),
			ipv4FromNetworkOrder(event.IPv4Daddr),
			ntohs(event.DestPort),
		)
	}
	if event.Reason == bootstrapDHCPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=[%s]:%d dst=[%s]:%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			ntohs(event.SourcePort),
			net.IP(event.IPv6Daddr[:]),
			ntohs(event.DestPort),
			event.VLANDepth,
		)
	}
	if event.Reason == bootstrapICMPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s dst=%s type=%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			net.IP(event.IPv6Daddr[:]),
			event.ICMPv6Type,
			event.VLANDepth,
		)
	}

	return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d eth_proto=0x%04x vlan_depth=%d",
		reason,
		event.Ifindex,
		event.EthProto,
		event.VLANDepth,
	)
}

func interfaceNames(ifaces []net.Interface) string {
	names := make([]string, 0, len(ifaces))
	for _, iface := range ifaces {
		names = append(names, iface.Name)
	}
	return strings.Join(names, ", ")
}

func boolByte(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

func ntohs(value uint16) uint16 {
	return value<<8 | value>>8
}

func htons(value uint16) uint16 {
	return ntohs(value)
}

func ipv4FromNetworkOrder(value uint32) net.IP {
	return net.IPv4(byte(value), byte(value>>8), byte(value>>16), byte(value>>24))
}

func ipv4Key(addr netip.Addr) uint32 {
	octets := addr.As4()
	return binary.LittleEndian.Uint32(octets[:])
}

func ipv6Key(addr netip.Addr) ipv6AddrKey {
	var key ipv6AddrKey
	octets := addr.As16()
	copy(key.Addr[:], octets[:])
	return key
}
