//go:build linux

package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/netip"
	"os"
	"os/signal"
	"regexp"
	"sort"
	"strings"
	"syscall"

	"github.com/asciimoth/killswitch/internal/policy"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

const (
	bootstrapARP    = 1
	bootstrapDHCPv4 = 2
	bootstrapDHCPv6 = 3
	bootstrapICMPv6 = 4

	ipProtoTCP = policy.IPProtoTCP
	ipProtoUDP = policy.IPProtoUDP

	defaultConfigPath = "/etc/killswitch/killswitch.json"
)

// runtimeConfig mirrors struct runtime_config in killswitch.c. Keep this type
// byte-sized so map updates are ABI-stable across Go and C.
type runtimeConfig struct {
	AllowAll uint8
	EnableV4 uint8
	EnableV6 uint8
	Reserved uint8
}

// bootstrapEvent mirrors struct bootstrap_event in killswitch.c. The eBPF
// program emits only bootstrap pass events so this channel remains low volume.
type bootstrapEvent struct {
	TimestampNS uint64
	Ifindex     uint32
	EthProto    uint16
	Reason      uint8
	IPProto     uint8
	IPv4Saddr   uint32
	IPv4Daddr   uint32
	IPv6Saddr   [16]byte
	IPv6Daddr   [16]byte
	SourcePort  uint16
	DestPort    uint16
	ICMPv6Type  uint8
	VLANDepth   uint8
	Reserved    uint16
}

// portKey mirrors struct port_key in killswitch.c. Ports are stored in network
// byte order because the eBPF parser compares them directly with packet fields.
type portKey struct {
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

// ipv6AddrKey mirrors struct ipv6_addr_key in killswitch.c.
type ipv6AddrKey struct {
	Addr [16]byte
}

// hostport4Key mirrors struct hostport4_key in killswitch.c. Explicit padding
// keeps the Go value layout aligned with the C map key ABI generated by clang.
type hostport4Key struct {
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

// hostport6Key mirrors struct hostport6_key in killswitch.c.
type hostport6Key struct {
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type options struct {
	InterfaceTypes          []string
	InterfaceNames          []string
	InterfaceRegexps        []string
	IgnoredInterfaceTypes   []string
	IgnoredInterfaceNames   []string
	IgnoredInterfaceRegexps []string
	AllowAll                bool
	EnableV4                bool
	EnableV6                bool
	AllowedMarks            []uint32
	AllowedPorts            []portKey
	AllowedV4Hosts          []uint32
	AllowedV6Hosts          []ipv6AddrKey
	AllowedV4Pairs          []hostport4Key
	AllowedV6Pairs          []hostport6Key
}

type configFile struct {
	InterfaceTypes          []string `json:"interface_types"`
	InterfaceNames          []string `json:"interface_names"`
	InterfaceRegexps        []string `json:"interface_regexps"`
	IgnoredInterfaceTypes   []string `json:"ignored_interface_types"`
	IgnoredInterfaceNames   []string `json:"ignored_interface_names"`
	IgnoredInterfaceRegexps []string `json:"ignored_interface_regexps"`
	AllowAll                bool     `json:"allow_all"`
	EnableV4                bool     `json:"enable_v4"`
	EnableV6                bool     `json:"enable_v6"`
	AllowedMarks            []string `json:"allowed_marks"`
	AllowedPorts            []string `json:"allowed_ports"`
	AllowedV4Hosts          []string `json:"allowed_v4_hosts"`
	AllowedV6Hosts          []string `json:"allowed_v6_hosts"`
	AllowedV4Pairs          []string `json:"allowed_v4_hostports"`
	AllowedV6Pairs          []string `json:"allowed_v6_hostports"`
}

type interfaceInfo struct {
	Index int
	Name  string
	Type  string
}

type attachedInterface struct {
	link link.Link
	info interfaceInfo
}

type egressManager struct {
	program  *ebpf.Program
	attached map[int]attachedInterface
}

func main() {
	configPath, err := parseArgs(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}

	opts, err := loadOptions(configPath, os.Stdin)
	if err != nil {
		log.Fatal(err)
	}

	if err := run(context.Background(), opts); err != nil {
		log.Fatal(err)
	}
}

func parseArgs(args []string) (string, error) {
	switch len(args) {
	case 0:
		return defaultConfigPath, nil
	case 1:
		return args[0], nil
	default:
		return "", fmt.Errorf("expected at most one config path argument, got: %s", strings.Join(args, " "))
	}
}

func loadOptions(configPath string, stdin io.Reader) (options, error) {
	var reader io.Reader
	if configPath == "-" {
		log.Print("Loading config from stdin")
		reader = stdin
	} else {
		log.Printf("Loading config from %s", configPath)
		file, err := os.Open(configPath)
		if err != nil {
			return options{}, fmt.Errorf("open config %q: %w", configPath, err)
		}
		defer file.Close() //nolint:errcheck
		reader = file
	}

	var cfg configFile
	decoder := json.NewDecoder(reader)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&cfg); err != nil {
		return options{}, fmt.Errorf("decode config: %w", err)
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return options{}, errors.New("decode config: multiple JSON values")
	}

	return configToOptions(cfg)
}

func configToOptions(cfg configFile) (options, error) {
	opts := options{
		InterfaceTypes:          cfg.InterfaceTypes,
		InterfaceNames:          cfg.InterfaceNames,
		InterfaceRegexps:        cfg.InterfaceRegexps,
		IgnoredInterfaceTypes:   cfg.IgnoredInterfaceTypes,
		IgnoredInterfaceNames:   cfg.IgnoredInterfaceNames,
		IgnoredInterfaceRegexps: cfg.IgnoredInterfaceRegexps,
		AllowAll:                cfg.AllowAll,
		EnableV4:                cfg.EnableV4,
		EnableV6:                cfg.EnableV6,
	}
	if len(opts.InterfaceTypes) == 0 && len(opts.InterfaceNames) == 0 && len(opts.InterfaceRegexps) == 0 {
		return options{}, errors.New("at least one interface_types, interface_names, or interface_regexps entry is required")
	}

	for _, pattern := range opts.InterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return options{}, fmt.Errorf("compile interface regexp %q: %w", pattern, err)
		}
	}
	for _, pattern := range opts.IgnoredInterfaceRegexps {
		if _, err := regexp.Compile(pattern); err != nil {
			return options{}, fmt.Errorf("compile ignored interface regexp %q: %w", pattern, err)
		}
	}
	var err error
	if opts.AllowedMarks, err = policy.ParseAllowedMarks(cfg.AllowedMarks); err != nil {
		return options{}, err
	}
	if opts.AllowedPorts, err = allowedPortKeys(cfg.AllowedPorts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Hosts, err = allowedV4HostKeys(cfg.AllowedV4Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Hosts, err = allowedV6HostKeys(cfg.AllowedV6Hosts); err != nil {
		return options{}, err
	}
	if opts.AllowedV4Pairs, err = allowedV4HostportKeys(cfg.AllowedV4Pairs); err != nil {
		return options{}, err
	}
	if opts.AllowedV6Pairs, err = allowedV6HostportKeys(cfg.AllowedV6Pairs); err != nil {
		return options{}, err
	}

	return opts, nil
}

func run(parent context.Context, opts options) error {
	if opts.AllowAll {
		log.Print("WARNING: AllowAll is enabled; protected interfaces will pass all traffic")
	}

	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock rlimit: %w", err)
	}

	var objs killswitchObjects
	if err := loadKillswitchObjects(&objs, nil); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}
	defer objs.Close() //nolint:errcheck

	if err := writeRuntimeConfig(objs.RuntimeConfig, runtimeConfig{
		AllowAll: boolByte(opts.AllowAll),
		EnableV4: boolByte(opts.EnableV4),
		EnableV6: boolByte(opts.EnableV6),
	}); err != nil {
		return err
	}
	if err := writeAllowlists(&objs, opts); err != nil {
		return err
	}

	signalCtx, stop := signal.NotifyContext(parent, os.Interrupt, syscall.SIGTERM)
	defer stop()
	ctx, cancel := context.WithCancel(signalCtx)
	defer cancel()

	reader, err := ringbuf.NewReader(objs.BootstrapEvents)
	if err != nil {
		return fmt.Errorf("open bootstrap event ring buffer: %w", err)
	}
	defer reader.Close() //nolint:errcheck

	go func() {
		<-ctx.Done()
		_ = reader.Close()
	}()

	log.Printf("Runtime config: allow_all=%t enable_v4=%t enable_v6=%t", opts.AllowAll, opts.EnableV4, opts.EnableV6)
	log.Printf("Allowlists: marks=%d ports=%d v4_hosts=%d v6_hosts=%d v4_hostports=%d v6_hostports=%d",
		len(opts.AllowedMarks),
		len(opts.AllowedPorts),
		len(opts.AllowedV4Hosts),
		len(opts.AllowedV6Hosts),
		len(opts.AllowedV4Pairs),
		len(opts.AllowedV6Pairs),
	)

	errCh := make(chan error, 2)
	go func() {
		if err := readBootstrapEvents(reader); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errCh <- err
		}
	}()

	manager := newEgressManager(objs.KillswitchEgress)
	defer manager.close()

	go func() {
		if err := watchInterfaces(ctx, manager, opts); err != nil {
			errCh <- err
		}
	}()

	select {
	case <-ctx.Done():
		return nil
	case err := <-errCh:
		cancel()
		return err
	}
}

func selectedInterfaces(opts options) ([]interfaceInfo, error) {
	all, err := listInterfaces()
	if err != nil {
		return nil, fmt.Errorf("list interfaces: %w", err)
	}
	return selectInterfaces(all, opts)
}

func listInterfaces() ([]interfaceInfo, error) {
	links, err := netlink.LinkList()
	if err != nil {
		return nil, err
	}

	all := make([]interfaceInfo, 0, len(links))
	for _, l := range links {
		attrs := l.Attrs()
		if attrs == nil {
			continue
		}
		all = append(all, interfaceInfo{
			Index: attrs.Index,
			Name:  attrs.Name,
			Type:  l.Type(),
		})
	}
	return all, nil
}

func selectInterfaces(all []interfaceInfo, opts options) ([]interfaceInfo, error) {
	var selected []interfaceInfo
	for _, iface := range all {
		matches, err := interfaceMatchesSelectors(iface, opts)
		if err != nil {
			return nil, err
		}
		if matches {
			selected = append(selected, iface)
		}
	}

	sort.Slice(selected, func(i, j int) bool {
		return selected[i].Name < selected[j].Name
	})
	return selected, nil
}

func writeRuntimeConfig(m *ebpf.Map, config runtimeConfig) error {
	var key uint32
	if err := m.Update(key, config, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("update runtime_config map: %w", err)
	}
	return nil
}

func writeAllowlists(objs *killswitchObjects, opts options) error {
	if err := writeAllowedMarks(objs.AllowedMarks, opts.AllowedMarks); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedPorts, opts.AllowedPorts, "allowed_ports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hosts, opts.AllowedV4Hosts, "allowed_v4_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hosts, opts.AllowedV6Hosts, "allowed_v6_hosts"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV4Hostports, opts.AllowedV4Pairs, "allowed_v4_hostports"); err != nil {
		return err
	}
	if err := writeAllowedMap(objs.AllowedV6Hostports, opts.AllowedV6Pairs, "allowed_v6_hostports"); err != nil {
		return err
	}
	return nil
}

func writeAllowedMarks(m *ebpf.Map, marks []uint32) error {
	return writeAllowedMap(m, marks, "allowed_marks")
}

func writeAllowedMap[K comparable](m *ebpf.Map, keys []K, name string) error {
	var allowed uint8 = 1
	for _, key := range keys {
		if err := m.Update(key, allowed, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("update %s map: %w", name, err)
		}
	}
	return nil
}

func allowedPortKeys(values []string) ([]portKey, error) {
	rules, err := policy.ParseAllowedPorts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]portKey, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, portKey{Dport: htons(rule.Port), Protocol: rule.Protocol})
	}
	return keys, nil
}

func allowedV4HostKeys(values []string) ([]uint32, error) {
	addrs, err := policy.ParseAllowedV4Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]uint32, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv4Key(addr))
	}
	return keys, nil
}

func allowedV6HostKeys(values []string) ([]ipv6AddrKey, error) {
	addrs, err := policy.ParseAllowedV6Hosts(values)
	if err != nil {
		return nil, err
	}
	keys := make([]ipv6AddrKey, 0, len(addrs))
	for _, addr := range addrs {
		keys = append(keys, ipv6Key(addr))
	}
	return keys, nil
}

func allowedV4HostportKeys(values []string) ([]hostport4Key, error) {
	rules, err := policy.ParseAllowedV4Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport4Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport4Key{
			Daddr:    ipv4Key(rule.AddrPort.Addr()),
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func allowedV6HostportKeys(values []string) ([]hostport6Key, error) {
	rules, err := policy.ParseAllowedV6Hostports(values)
	if err != nil {
		return nil, err
	}
	keys := make([]hostport6Key, 0, len(rules))
	for _, rule := range rules {
		keys = append(keys, hostport6Key{
			Daddr:    ipv6Key(rule.AddrPort.Addr()).Addr,
			Dport:    htons(rule.AddrPort.Port()),
			Protocol: rule.Protocol,
		})
	}
	return keys, nil
}

func readBootstrapEvents(reader *ringbuf.Reader) error {
	for {
		record, err := reader.Read()
		if err != nil {
			return err
		}

		event, err := parseBootstrapEvent(record.RawSample)
		if err != nil {
			log.Printf("parse bootstrap event: %s", err)
			continue
		}
		log.Print(formatBootstrapEvent(event))
	}
}

func parseBootstrapEvent(raw []byte) (bootstrapEvent, error) {
	var event bootstrapEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &event); err != nil {
		return bootstrapEvent{}, err
	}
	return event, nil
}

func formatBootstrapEvent(event bootstrapEvent) string {
	reason := "unknown"
	switch event.Reason {
	case bootstrapARP:
		reason = "arp"
	case bootstrapDHCPv4:
		reason = "dhcpv4"
	case bootstrapDHCPv6:
		reason = "dhcpv6"
	case bootstrapICMPv6:
		reason = "icmpv6_nd"
	}

	if event.Reason == bootstrapDHCPv4 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s:%d dst=%s:%d",
			reason,
			event.Ifindex,
			ipv4FromNetworkOrder(event.IPv4Saddr),
			ntohs(event.SourcePort),
			ipv4FromNetworkOrder(event.IPv4Daddr),
			ntohs(event.DestPort),
		)
	}
	if event.Reason == bootstrapDHCPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=[%s]:%d dst=[%s]:%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			ntohs(event.SourcePort),
			net.IP(event.IPv6Daddr[:]),
			ntohs(event.DestPort),
			event.VLANDepth,
		)
	}
	if event.Reason == bootstrapICMPv6 {
		return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d src=%s dst=%s type=%d vlan_depth=%d",
			reason,
			event.Ifindex,
			net.IP(event.IPv6Saddr[:]),
			net.IP(event.IPv6Daddr[:]),
			event.ICMPv6Type,
			event.VLANDepth,
		)
	}

	return fmt.Sprintf("bootstrap pass: reason=%s ifindex=%d eth_proto=0x%04x vlan_depth=%d",
		reason,
		event.Ifindex,
		event.EthProto,
		event.VLANDepth,
	)
}

func newEgressManager(program *ebpf.Program) *egressManager {
	return &egressManager{
		program:  program,
		attached: make(map[int]attachedInterface),
	}
}

func (m *egressManager) reconcileCurrent(opts options, strict bool) (bool, error) {
	selected, err := selectedInterfaces(opts)
	if err != nil {
		return false, err
	}
	if len(selected) == 0 {
		log.Print("No interfaces currently match the configured selectors")
	}
	return m.reconcile(selected, strict)
}

func (m *egressManager) reconcile(selected []interfaceInfo, strict bool) (bool, error) {
	desired := make(map[int]interfaceInfo, len(selected))
	for _, iface := range selected {
		desired[iface.Index] = iface
	}

	changed := false
	for index, attached := range m.attached {
		if _, ok := desired[index]; ok {
			continue
		}
		if err := attached.link.Close(); err != nil {
			log.Printf("ERROR: detach tc egress program from %s(index %d type %s): %s", attached.info.Name, attached.info.Index, attached.info.Type, err)
		} else {
			log.Printf("Detached tc egress program from %s(index %d type %s)", attached.info.Name, attached.info.Index, attached.info.Type)
		}
		delete(m.attached, index)
		changed = true
	}

	var attachErr error
	for _, iface := range selected {
		if attached, ok := m.attached[iface.Index]; ok {
			attached.info = iface
			m.attached[iface.Index] = attached
			continue
		}

		l, err := link.AttachTCX(link.TCXOptions{
			Interface: iface.Index,
			Program:   m.program,
			Attach:    ebpf.AttachTCXEgress,
		})
		if err != nil {
			err = fmt.Errorf("attach tc egress program to %s(index %d type %s): %w", iface.Name, iface.Index, iface.Type, err)
			log.Printf("ERROR: %s", err)
			attachErr = errors.Join(attachErr, err)
			continue
		}
		m.attached[iface.Index] = attachedInterface{link: l, info: iface}
		log.Printf("Attached tc egress program to %s(index %d type %s)", iface.Name, iface.Index, iface.Type)
		changed = true
	}

	if changed {
		log.Printf("Kill switch attached to: %s", interfaceNames(m.attachedInterfaces()))
	}
	if strict {
		return changed, attachErr
	}
	return changed, nil
}

func (m *egressManager) attachedInterfaces() []interfaceInfo {
	ifaces := make([]interfaceInfo, 0, len(m.attached))
	for _, attached := range m.attached {
		ifaces = append(ifaces, attached.info)
	}
	sort.Slice(ifaces, func(i, j int) bool {
		return ifaces[i].Name < ifaces[j].Name
	})
	return ifaces
}

func (m *egressManager) close() {
	for index, attached := range m.attached {
		if err := attached.link.Close(); err != nil {
			log.Printf("closing link for %s(index %d): %s", attached.info.Name, attached.info.Index, err)
		}
		delete(m.attached, index)
	}
}

func watchInterfaces(ctx context.Context, manager *egressManager, opts options) error {
	updates := make(chan netlink.LinkUpdate, 32)
	done := make(chan struct{})
	defer close(done)

	subscribeErrs := make(chan error, 1)
	errCallback := func(err error) {
		select {
		case subscribeErrs <- err:
		default:
			log.Printf("ERROR: netlink link watcher: %s", err)
		}
	}

	if err := netlink.LinkSubscribeWithOptions(updates, done, netlink.LinkSubscribeOptions{
		ErrorCallback: errCallback,
	}); err != nil {
		return fmt.Errorf("subscribe to netlink link updates: %w", err)
	}

	if _, err := manager.reconcileCurrent(opts, true); err != nil {
		return err
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case err := <-subscribeErrs:
			return fmt.Errorf("netlink link watcher: %w", err)
		case update := <-updates:
			if !manager.shouldReconcileLinkUpdate(update, opts) {
				continue
			}
			logLinkUpdate(update)
			if _, err := manager.reconcileCurrent(opts, false); err != nil {
				log.Printf("ERROR: reconcile interfaces after netlink update: %s", err)
			}
		}
	}
}

func (m *egressManager) shouldReconcileLinkUpdate(update netlink.LinkUpdate, opts options) bool {
	if update.Link == nil || update.Link.Attrs() == nil { //nolint:staticcheck
		return true
	}

	attrs := update.Link.Attrs() //nolint:staticcheck
	switch update.Header.Type {
	case unix.RTM_DELLINK:
		return m.isAttached(attrs.Index)
	case unix.RTM_NEWLINK:
		matches, err := interfaceMatchesSelectors(interfaceInfo{
			Index: attrs.Index,
			Name:  attrs.Name,
			Type:  update.Link.Type(), //nolint:staticcheck
		}, opts)
		if err != nil {
			log.Printf("ERROR: match netlink link update selectors: %s", err)
			return true
		}
		return matches != m.isAttached(attrs.Index)
	default:
		return false
	}
}

func (m *egressManager) isAttached(index int) bool {
	_, ok := m.attached[index]
	return ok
}

func interfaceMatchesSelectors(iface interfaceInfo, opts options) (bool, error) {
	ignored, err := interfaceMatchesIgnoreSelectors(iface, opts)
	if err != nil {
		return false, err
	}
	if ignored {
		return false, nil
	}

	for _, typ := range opts.InterfaceTypes {
		if iface.Type == typ {
			return true, nil
		}
	}
	for _, name := range opts.InterfaceNames {
		if iface.Name == name {
			return true, nil
		}
	}
	for _, pattern := range opts.InterfaceRegexps {
		matches, err := regexp.MatchString(pattern, iface.Name)
		if err != nil {
			return false, fmt.Errorf("compile interface regexp %q: %w", pattern, err)
		}
		if matches {
			return true, nil
		}
	}
	return false, nil
}

func interfaceMatchesIgnoreSelectors(iface interfaceInfo, opts options) (bool, error) {
	if iface.Name == "lo" {
		return true, nil
	}
	for _, typ := range opts.IgnoredInterfaceTypes {
		if iface.Type == typ {
			return true, nil
		}
	}
	for _, name := range opts.IgnoredInterfaceNames {
		if iface.Name == name {
			return true, nil
		}
	}
	for _, pattern := range opts.IgnoredInterfaceRegexps {
		matches, err := regexp.MatchString(pattern, iface.Name)
		if err != nil {
			return false, fmt.Errorf("compile ignored interface regexp %q: %w", pattern, err)
		}
		if matches {
			return true, nil
		}
	}
	return false, nil
}

func logLinkUpdate(update netlink.LinkUpdate) {

	if update.Link == nil || update.Link.Attrs() == nil { //nolint:staticcheck
		log.Print("Netlink link update received")
		return
	} //nolint:staticcheck
	attrs := update.Link.Attrs() //nolint:staticcheck

	log.Printf("Netlink link update: %s(index %d type %s)", attrs.Name, attrs.Index, update.Link.Type()) //nolint:staticcheck
}

func interfaceNames(ifaces []interfaceInfo) string {
	names := make([]string, 0, len(ifaces))
	for _, iface := range ifaces {
		names = append(names, iface.Name)
	}
	return strings.Join(names, ", ")
}

func boolByte(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

func ntohs(value uint16) uint16 {
	return value<<8 | value>>8
}

func htons(value uint16) uint16 {
	return ntohs(value)
}

func ipv4FromNetworkOrder(value uint32) net.IP {
	return net.IPv4(byte(value), byte(value>>8), byte(value>>16), byte(value>>24))
}

func ipv4Key(addr netip.Addr) uint32 {
	octets := addr.As4()
	return binary.LittleEndian.Uint32(octets[:])
}

func ipv6Key(addr netip.Addr) ipv6AddrKey {
	var key ipv6AddrKey
	octets := addr.As16()
	copy(key.Addr[:], octets[:])
	return key
}
