//go:build linux

package main

import (
	"net/netip"
	"sync"

	"github.com/asciimoth/killswitch/internal/policy"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

const (
	bootstrapARP    = 1
	bootstrapDHCPv4 = 2
	bootstrapDHCPv6 = 3
	bootstrapICMPv6 = 4

	ipProtoTCP = policy.IPProtoTCP
	ipProtoUDP = policy.IPProtoUDP

	defaultConfigPath = "/etc/killswitch/killswitch.json"
)

// runtimeConfig mirrors struct runtime_config in killswitch.c. Keep this type
// byte-sized so map updates are ABI-stable across Go and C.
type runtimeConfig struct {
	AllowAll uint8
	EnableV4 uint8
	EnableV6 uint8
	Reserved uint8
}

// bootstrapEvent mirrors struct bootstrap_event in killswitch.c. The eBPF
// program emits only bootstrap pass events so this channel remains low volume.
type bootstrapEvent struct {
	TimestampNS uint64
	Ifindex     uint32
	EthProto    uint16
	Reason      uint8
	IPProto     uint8
	IPv4Saddr   uint32
	IPv4Daddr   uint32
	IPv6Saddr   [16]byte
	IPv6Daddr   [16]byte
	SourcePort  uint16
	DestPort    uint16
	ICMPv6Type  uint8
	VLANDepth   uint8
	Reserved    uint16
}

// portKey mirrors struct port_key in killswitch.c. Ports are stored in network
// byte order because the eBPF parser compares them directly with packet fields.
type portKey struct {
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

type markPolicyKey struct {
	Ifindex uint32
	Mark    uint32
}

type portPolicyKey struct {
	Ifindex  uint32
	Dport    uint16
	Protocol uint8
	Reserved uint8
}

// ipv6AddrKey stores an unscoped IPv6 address in parsed allow-rule config.
type ipv6AddrKey struct {
	Addr [16]byte
}

type v4HostPolicyKey struct {
	Ifindex uint32
	Daddr   uint32
}

type v6HostPolicyKey struct {
	Ifindex uint32
	Addr    [16]byte
}

// hostport4Key mirrors struct hostport4_key in killswitch.c. Explicit padding
// keeps the Go value layout aligned with the C map key ABI generated by clang.
type hostport4Key struct {
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

// hostport6Key mirrors struct hostport6_key in killswitch.c.
type hostport6Key struct {
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type hostport4PolicyKey struct {
	Ifindex   uint32
	Daddr     uint32
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type hostport6PolicyKey struct {
	Ifindex   uint32
	Daddr     [16]byte
	Dport     uint16
	Reserved0 uint16
	Protocol  uint8
	Reserved1 [3]byte
}

type options struct {
	InterfaceTypes          []string
	InterfaceNames          []string
	InterfaceRegexps        []string
	IgnoredInterfaceTypes   []string
	IgnoredInterfaceNames   []string
	IgnoredInterfaceRegexps []string
	AdminAPI                adminAPIOptions
	SocksProxy              socksProxyOptions
	allowRules
	Rulesets []ruleset
}

type allowRules struct {
	AllowAll       bool
	EnableV4       bool
	EnableV6       bool
	AllowedMarks   []uint32
	AllowedPorts   []portKey
	AllowedV4Hosts []uint32
	AllowedV6Hosts []ipv6AddrKey
	AllowedV4Pairs []hostport4Key
	AllowedV6Pairs []hostport6Key
}

type ruleset struct {
	Name     string
	Disabled bool
	MatchAll bool
	Trigger  rulesetTrigger
	allowRules
}

type rulesetTrigger struct {
	InterfaceTypes   []string
	InterfaceNames   []string
	InterfaceRegexps []string
	IPAddrs          []netip.Addr
	SSIDs            []string
	BSSIDs           []string
	GatewayMACs      []string
}

type configFile struct {
	InterfaceTypes          []string                 `json:"interface_types"`
	InterfaceNames          []string                 `json:"interface_names"`
	InterfaceRegexps        []string                 `json:"interface_regexps"`
	IgnoredInterfaceTypes   []string                 `json:"ignored_interface_types"`
	IgnoredInterfaceNames   []string                 `json:"ignored_interface_names"`
	IgnoredInterfaceRegexps []string                 `json:"ignored_interface_regexps"`
	AdminAPI                adminAPIConfig           `json:"admin_api"`
	SocksProxy              socksProxyConfig         `json:"socks_proxy"`
	AllowAll                bool                     `json:"allow_all"`
	EnableV4                bool                     `json:"enable_v4"`
	EnableV6                bool                     `json:"enable_v6"`
	AllowedMarks            []string                 `json:"allowed_marks"`
	AllowedPorts            []string                 `json:"allowed_ports"`
	AllowedV4Hosts          []string                 `json:"allowed_v4_hosts"`
	AllowedV6Hosts          []string                 `json:"allowed_v6_hosts"`
	AllowedV4Pairs          []string                 `json:"allowed_v4_hostports"`
	AllowedV6Pairs          []string                 `json:"allowed_v6_hostports"`
	Rulesets                map[string]rulesetConfig `json:"rulesets"`
}

type rulesetConfig struct {
	Disabled       bool          `json:"disabled"`
	Match          string        `json:"match"`
	MatchAll       bool          `json:"match_all"`
	Trigger        triggerConfig `json:"trigger"`
	AllowAll       bool          `json:"allow_all"`
	EnableV4       bool          `json:"enable_v4"`
	EnableV6       bool          `json:"enable_v6"`
	AllowedMarks   []string      `json:"allowed_marks"`
	AllowedPorts   []string      `json:"allowed_ports"`
	AllowedV4Hosts []string      `json:"allowed_v4_hosts"`
	AllowedV6Hosts []string      `json:"allowed_v6_hosts"`
	AllowedV4Pairs []string      `json:"allowed_v4_hostports"`
	AllowedV6Pairs []string      `json:"allowed_v6_hostports"`
}

type triggerConfig struct {
	InterfaceTypes   []string `json:"interface_types"`
	InterfaceNames   []string `json:"interface_names"`
	InterfaceRegexps []string `json:"interface_regexps"`
	IPAddrs          []string `json:"ip_addrs"`
	SSIDs            []string `json:"ssids"`
	BSSIDs           []string `json:"bssids"`
	GatewayMACs      []string `json:"gateway_macs"`
}

type interfaceInfo struct {
	Index       int
	Name        string
	Type        string
	Addrs       []netip.Addr
	SSID        string
	BSSID       string
	GatewayMACs []string
}

type attachedInterface struct {
	link link.Link
	info interfaceInfo
}

type egressManager struct {
	mu       sync.Mutex
	program  *ebpf.Program
	attached map[int]attachedInterface
}

type policyManager struct {
	mu            sync.Mutex
	objs          *killswitchObjects
	opts          options
	socksProxy    socksProxyState
	tmpRulesets   map[string]temporaryRuleset
	forceRulesets map[string]map[string]map[string]int
	current       map[int]interfacePolicy
	set           bool
}

type interfacePolicy struct {
	Info              interfaceInfo
	Rules             allowRules
	ActiveRulesets    []string
	ForcedRulesets    []string
	TemporaryRulesets []string
}
